%% run_F16_TS_diagram
%   Builds the Brandt-discipline validation stack (f16_brandt_stack: Brandt
%   disciplines through the FRAMEWORK mission/constraint analyses -- see that
%   builder's header) and draws the dimensional T-S sizing diagram
%   (src/sizing/TSDiagram.m): every point is a SIZED aircraft with a
%   converged TOGW, constraints traced as T(S)/S(T) curves, fuel-burn
%   contours superimposed, and the actual aircraft marked
%   [docs/reference_extracts/metabook_data.md -- Ch. 4 S4.12, Fig. 4.7's
%   "Actual 777-200LR" marker precedent].
%
%   Style/wiring follows run_F16_constraint_diagram.m (caller owns discipline
%   construction); output-export pattern follows the sanity_checks scripts
%   (console + files into the gitignored examples/F16A/output/).
%
%   EXPECTED CONTEXT: the framework L2 mission over the Brandt disciplines
%   burns ~+8.9% vs the Brandt Miss-tab (BY DESIGN -- see sanity_checks/
%   mission_brandt_comparison.m), so converged weights on this diagram sit
%   ~1.5-2% above Brandt's 31,377 lbf at the (T = 23,770, S = 300) marker.

% Brandt validation stack + the T-S diagram orchestrator. TSDiagram mutates
% the shared geom/prop/wts objects in place during the scan (see its header);
% the stack is built fresh here and used for nothing else afterwards.
objs = f16_brandt_stack();
ts = TSDiagram(objs.aero, objs.prop, objs.wts, objs.geom, objs.miss, ...
    objs.con, objs.tail);

% Uniform grids (TSDiagram.plot's feasible-region shading assumes uniform
% spacing). Ranges bracket the F-16A actual point (S = 300 ft^2,
% T = 23,770 lbf) with margin on both sides.
S_grid = linspace(220, 420, 11);    % ft^2
T_grid = linspace(12e3, 40e3, 11);  % lbf

% Actual-aircraft marker [metabook Fig. 4.7 marker precedent]:
% S = 300 ft^2 [Brandt Main!B18], T_SL(AB) = 23,770 lbf [Brandt Engn!T_AB_SLS].
actual = struct('T', 23770, 'S', 300, 'label', "F-16A (Brandt)");

% Converged TOGW at the actual aircraft's (T, S) cell [metabook Algorithm 2],
% for the results export. Compare against Brandt's 31,377 lbf (expect the
% BY-DESIGN ~+1.5-2% mission offset -- see header).
W0_actual = ts.converge_W0(actual.T, actual.S);
fprintf('Converged W_TO at (T = %.0f lbf, S = %.0f ft^2): %.1f lbf (Brandt = 31377, %+.2f%%)\n', ...
    actual.T, actual.S, W0_actual, 100*(W0_actual - 31377)/31377);

% Fuel-burn/TOGW grid for the results export [metabook S4.12 objective
% contours]. ts.plot below re-runs the same grid internally (it takes no
% precomputed data); the repeat is warm-started cell to cell and this is an
% offline study script, so the duplicate cost is accepted for a simple API.
fg = ts.fuel_grid(T_grid, S_grid);

% The diagram itself [metabook Fig. 4.7].
fig = ts.plot('S_grid', S_grid, 'T_grid', T_grid, 'actual', actual);

% ---- Exports into the gitignored output/ (sanity_checks pattern) -------- %
outdir = fullfile(fileparts(mfilename('fullpath')), '..', 'output');
if ~exist(outdir, 'dir'), mkdir(outdir); end

exportgraphics(fig, fullfile(outdir, 'F16_TS_diagram.png'), 'Resolution', 200);

results = struct( ...
    'stack',      'Brandt disciplines x framework mission/constraints (f16_brandt_stack)', ...
    'S_grid_ft2', S_grid, ...
    'T_grid_lbf', T_grid, ...
    'W0_lbf',     fg.W0, ...        % converged TOGW per (T, S) cell, NaN = infeasible
    'W_fuel_lbf', fg.W_fuel, ...    % mission fuel per (T, S) cell
    'actual',     struct('T_lbf', actual.T, 'S_ft2', actual.S, ...
                         'label', actual.label, 'W0_converged_lbf', W0_actual, ...
                         'W_TO_brandt_lbf', 31377));
fid = fopen(fullfile(outdir, 'F16_TS_diagram.json'), 'w');
fwrite(fid, jsonencode(results, 'PrettyPrint', true));
fclose(fid);

L = strings(0, 1);
L(end+1) = "# F-16A T-S Sizing Diagram (Brandt validation stack)";
L(end+1) = "";
L(end+1) = "Generated by `studies/run_F16_TS_diagram.m` over `f16_brandt_stack()`.";
L(end+1) = "Every grid point is a sized aircraft with a converged TOGW [metabook Ch. 4 S4.12].";
L(end+1) = "";
L(end+1) = sprintf("- S grid: %.0f to %.0f ft^2 (%d points)", min(S_grid), max(S_grid), numel(S_grid));
L(end+1) = sprintf("- T grid: %.0f to %.0f lbf (%d points)", min(T_grid), max(T_grid), numel(T_grid));
L(end+1) = sprintf("- Converged W_TO at the F-16A marker (T = %.0f, S = %.0f): %.1f lbf (Brandt 31,377; %+.2f%%, mission offset BY DESIGN -- see mission_brandt_comparison.m)", ...
    actual.T, actual.S, W0_actual, 100*(W0_actual - 31377)/31377);
L(end+1) = sprintf("- Infeasible/unconverged cells (NaN): %d of %d", ...
    nnz(~isfinite(fg.W0)), numel(fg.W0));
L(end+1) = "";
L(end+1) = "Figure: `F16_TS_diagram.png`. Full grids: `F16_TS_diagram.json`.";
writelines(L, fullfile(outdir, 'F16_TS_diagram.md'));

fprintf('Wrote output/F16_TS_diagram.png, .json and .md\n');
