classdef GeometryLevel3 < GeometryModelLevel3
     %F16GEOMETRYSTUFF Summary of this class goes here
     %   Detailed explanation goes here

     properties
          % Organize by physical object; separate into tail (horizontal,
          % vertical), fuselage, etc?
          % I should definitely use structs for this. Organize into wings,
          % tails, fuselage.

          mainwings
          HT
          VT
          fuselage
          strakes
          design
     end

     methods


          function obj = GeometryLevel3(design)
               obj.mainwings = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'lambda', [], ...
                    'airfoil_type', []);

               obj.HT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'lambda', [], ...
                    'airfoil_type', []);

               obj.VT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'lambda', [], ...
                    'airfoil_type', []);

               obj.strakes = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'lambda', [], ...
                    'airfoil_type', []);

               obj.fuselage = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'L', [], ...
                    'W_max', [], ...
                    'h_max', []);

               obj.design = struct(...
                    'S_wet', [],...
                    'W_max', [], ...
                    'total_length', []);

               % Now load the design's geometry!
               if nargin > 0 && ~isempty(design)
                    GeometryUtils.loaddesigngeometry(obj, design)
               end

               % Get S_exposed for each component
               obj.mainwings.S_exposed = get_S_exposed(obj, obj.mainwings.tip_chord, obj.mainwings.exposed_rc, obj.mainwings.exposed_halfspan);
               obj.HT.S_exposed = get_S_exposed(obj, obj.HT.tip_chord, obj.HT.exposed_rc, obj.HT.exposed_halfspan);
               obj.VT.S_exposed = get_S_exposed(obj, obj.VT.tip_chord, obj.VT.exposed_rc, obj.VT.exposed_halfspan);

               % Get S_wet for each component
               obj.mainwings.S_wet = get_S_wet_wing(obj, obj.mainwings.S_exposed, obj.mainwings.tc);
               obj.HT.S_wet = get_S_wet_wing(obj, obj.HT.S_exposed, obj.HT.tc);
               obj.VT.S_wet = get_S_wet_wing(obj, obj.VT.S_exposed, obj.VT.tc);
               obj.fuselage.S_wet = get_S_wet_fuselage(obj, obj.design.total_length, obj.fuselage.W_max, obj.fuselage.h_max);
               % obj.fuselage.S_wet = get_S_wet_fuselage(obj, 46.50, 7.0, obj.fuselage.h_max);

          end

          % Add functions for estimating control surface sizing

          % Estimate the wetted area of the aircraft
          function output = get_design_S_wet(obj, W_TO)
               c = -0.1289; % Coefficient for fighter aircraft, given for S_wetrest equation, provided by Roskam's Aircraft Design Volume 1 (1985), Table 3.5.
               d = 0.7506; % Coefficient for fighter aicraft, given for S_wetrest equation, provided by Roskam's Aircraf Design Volume 1 (1985), Table 3.5.
               obj.design.S_wet = 10^(c) * W_TO^(d); % ft^2
               output = obj.design.S_wet;
          end

          % Size the tail
          function [S_HT, S_VT] = size_tail(obj, design, S_ref)
               [S_HT, S_VT] = Tail_Sizing_IV(obj, design.geom.wings.VerticalTail.c_VT, design.geom.wings.HorizontalTail.c_HT, design.geom.wings.Main.Spanft, S_ref, design.geom.fuselage.Fuselage.Lengthft, design.geom.wings.Main.MeanGeometricChord);
          end

          % Estimate exposed surface area (lifting surface)
          % Source: Brandt, "F16A", "Geom" sheet, cell H7.
          function output = get_S_exposed(geometry_obj, tip_length, exposed_rc, exposed_halfspan)
               output = exposed_halfspan*(exposed_rc + tip_length);
          end

          % Estimate exposed wetted areas (lifting surfaces)
          function output = get_S_wet_wing(geometry_obj, S_exposed, tc)
               output = S_exposed*(1.977 + 0.52*tc); % Brandt, "Geom" sheet, cell B13
          end

          % Estimate wetted area (fuselage) (Brandt's 2/3 cylinder + 1/3
          % cone approximation)
          function output = get_S_wet_fuselage(geometry_obj, fuselage_length, fuselage_max_width, max_height)
               output = (5/6) * fuselage_length * (fuselage_max_width + max_height)*2*pi/4;
          end

          % Estimate wing sweep at quarter-chord (deg)
          function output = get_sweep_qc(geometry_obj, b, LE_sweep_deg, root_chord, tip_chord)
               output = atand(tand(LE_sweep_deg) - (root_chord - tip_chord)/(2*b));
          end
     end

     methods (Access = private)

          % Size the tail
          function [S_HT, S_VT] = Tail_Sizing_IV(obj, c_VT, c_HT, b_W, S_ref, L_fus, Cbar_W)

               % NOTE: S_REF IS USED BUT ITS SUPPOSED TO BE S_REF OF THE
               % MAIN WINGS
               % Assuming tail located 90% down fuselage
               L_VT = L_fus*0.8;
               L_HT = L_fus*0.8; % Allow operator to adjust this, later.

               obj.VT.L = L_VT;
               obj.HT.L = L_HT;

               S_VT = c_VT*b_W*S_ref/obj.VT.L; % eq 6.28, 2nd edition

               S_HT = c_HT*Cbar_W*S_ref/obj.HT.L; % eq 6.29, 2nd edition

               obj.VT.S_ref = S_VT;
               obj.HT.S_ref = S_HT;

          end
     end
end