classdef GeometryLevel1 < GeometryModelLevel1
     %GEOMETRYLEVEL1 Summary of this class goes here
     %   Detailed explanation goes here

     properties
          mainwings
          HT
          VT
          fuselage
          design
     end

     methods
          function obj = GeometryLevel1(design)
               obj.mainwings = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.HT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.VT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.strakes = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.fuselage = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'L', [], ...
                    'W_max', [], ...
                    'h_max', []);

               obj.design = struct(...
                    'S_wet', [],...
                    'W_max', [], ...
                    'total_length', []);

               % Now load the design's geometry!
               if nargin > 0 && ~isempty(design)
                    GeometryUtils.loaddesigngeometry(obj, design)
               end

               % Get S_exposed for each component
               obj.mainwings.S_exposed = get_S_exposed(obj, obj.mainwings.tip_chord, obj.mainwings.exposed_rc, obj.mainwings.exposed_halfspan);
               obj.HT.S_exposed = get_S_exposed(obj, obj.HT.tip_chord, obj.HT.exposed_rc, obj.HT.exposed_halfspan);
               obj.VT.S_exposed = get_S_exposed(obj, obj.VT.tip_chord, obj.VT.exposed_rc, obj.VT.exposed_halfspan);

               % Get S_wet for each component
               obj.mainwings.S_wet = get_S_wet_wing(obj, obj.mainwings.S_exposed, obj.mainwings.tc);
               obj.HT.S_wet = get_S_wet_wing(obj, obj.HT.S_exposed, obj.HT.tc);
               obj.VT.S_wet = get_S_wet_wing(obj, obj.VT.S_exposed, obj.VT.tc);
               obj.fuselage.S_wet = get_S_wet_fuselage(obj, obj.design.total_length, obj.fuselage.W_max, obj.fuselage.h_max);
               % obj.fuselage.S_wet = get_S_wet_fuselage(obj, 46.50, 7.0, obj.fuselage.h_max);

          end

          function L_fuselage = get_fus_len(geometry_obj, aircraft_type, W_TO)
               if aircraft_type == "Sailplane - unpowered"
                    a = 0.86;
                    C = 0.48;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Sailplane - powered"
                    a = 0.71;
                    C = 0.48;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif (aircraft_type == "Homebuilt - metal") || (aircraft_type == "Homebuilt - wood")
                    a = 3.68;
                    C = 0.23;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Homebuilt - composite"
                    a = 3.50;
                    C = 0.23;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "General aviation - single engine"
                    a = 4.37;
                    C = 0.23;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "General aviation - twin engine"
                    a = 0.86;
                    C = 0.42;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Agricultural aircraft"
                    a = 4.04;
                    C = 0.23;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Twin turboprop"
                    a = 0.37;
                    C = 0.51;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Flying boat"
                    a = 1.05;
                    C = 0.40;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Jet trainer"
                    a = 0.79;
                    C = 0.41;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif aircraft_type == "Jet fighter"
                    a = 0.93;
                    C = 0.39;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif (aircraft_type == "Military cargo") || (aircraft_type == "Military bomber")
                    a = 0.23;
                    C = 0.50;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               elseif (aircraft_type == "Jet transport")
                    a = 0.67;
                    C = 0.43;
                    output = geometry_obj.compute_fus_len(a, C, W_TO);
               else
                    error("Unrecognized aircraft type.") % Include list of acceptable parameters
               end
               L_fuselage = output;
               geometry_obj.fuselage.L = L_fuselage;

          end

          % Estimate fuselage length based on historical trend
          function output = compute_fus_len(geometry_obj, a, C, W_TO)
               output = a*W_TO^(C); % Raymer, 6th ed, table 6.3
          end
     end

     methods (Access = private)

     end
end