classdef GeometryLevel2 < GeometryModelLevel2
     %F16GEOMETRYSTUFF Summary of this class goes here
     %   Detailed explanation goes here

     properties
          % Organize by physical object; separate into tail (horizontal,
          % vertical), fuselage, etc?
          % I should definitely use structs for this. Organize into wings,
          % tails, fuselage.

          mainwings
          HT
          VT
          fuselage
          strakes
          design
     end

     methods


          function obj = GeometryLevel2(design)
               obj.mainwings = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.HT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.VT = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.strakes = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'b', [], ...
                    'c_root', [], ...
                    'MeanGeometricChord', [], ...
                    'LE_sweep', [], ...
                    'QC_sweep', [], ...
                    'AR', [], ...
                    'xc', [], ...
                    'tc', [], ...
                    'exposed_halfspan', [], ...
                    'exposed_rc', [], ...
                    'tip_chord', [], ...
                    'airfoil_type', []);

               obj.fuselage = struct( ...
                    'S_ref', [], ...
                    'S_exposed', [], ...
                    'S_wet', [], ...
                    'L', [], ...
                    'W_max', [], ...
                    'h_max', []);

               obj.design = struct(...
                    'S_wet', [],...
                    'W_max', [], ...
                    'total_length', []);

               % Now load the design's geometry!
               if nargin > 0 && ~isempty(design)
                    GeometryUtils.loaddesigngeometry(obj, design)
               end

               % Get S_exposed for each component
               obj.mainwings.S_exposed = obj.get_S_exposed_wing(obj.mainwings.tip_chord, obj.mainwings.exposed_rc, obj.mainwings.exposed_halfspan);
               obj.HT.S_exposed = obj.get_S_exposed_wing(obj.HT.tip_chord, obj.HT.exposed_rc, obj.HT.exposed_halfspan);
               obj.VT.S_exposed = obj.get_S_exposed_wing(obj.VT.tip_chord, obj.VT.exposed_rc, obj.VT.exposed_halfspan);

               % Get S_wet for each component
               obj.mainwings.S_wet = obj.get_S_wet_wing(obj.mainwings.S_exposed, obj.mainwings.tc);
               obj.HT.S_wet = obj.get_S_wet_wing(obj.HT.S_exposed, obj.HT.tc);
               obj.VT.S_wet = obj.get_S_wet_wing(obj.VT.S_exposed, obj.VT.tc);
               obj.fuselage.S_wet = obj.compute_S_wet_body(design.geom.fuselage.Fuselage.Areasideft2, design.geom.fuselage.Fuselage.Areatopft2);
               % obj.fuselage.S_wet = get_S_wet_fuselage(obj, 46.50, 7.0, obj.fuselage.h_max);

          end

          % Add functions for estimating control surface sizing

          % Estimate the wetted area of the aircraft
          function output = get_design_S_wet(obj, W_TO)
               % (Have a way to use different coefficients for different
               % aircraft types!)
               c = -0.1289; % Coefficient for fighter aircraft, given for S_wet equation, provided by Roskam's Aircraft Design Volume 1 (1985), Table 3.5.
               d = 0.7506; % Coefficient for fighter aicraft, given for S_wet equation, provided by Roskam's Aircraf Design Volume 1 (1985), Table 3.5.
               obj.design.S_wet = 10^(c) * W_TO^(d); % ft^2
               output = obj.design.S_wet;
          end

          % Estimate exposed surface area (lifting surface)
          % Source: Brandt, "F16A", "Geom" sheet, cell H7.
          function output = get_S_exposed_wing(geometry_obj, tip_length, exposed_rc, exposed_halfspan)
               output = exposed_halfspan*(exposed_rc + tip_length);
          end

          % Estimate exposed wetted areas (lifting surfaces) (Wrapper)
          function S_wet_wing = get_S_wet_wing(geometry_obj, S_exposed, tc)
               if tc <= 0.05
                    S_wet_wing = geometry_obj.compute_S_wet_wing_lowtc(S_exposed);
               elseif tc > 0.05
                    S_wet_wing = geometry_obj.compute_S_wet_wing_hightc(S_exposed, tc);
               end
          end

          % Estimate wetted area (body)
          % "Body" = "fuselage + nose cone + whatever isn't the wings from
          % a silouetted side-view"
          % "Fuselage" = "the fuselage"
          function output = compute_S_wet_body(geometry_obj, A_top, A_side)
               output = 3.4*(A_top + A_side)/2; % Raymer, 6th ed, eq 7.13
          end
     end

     methods (Access = private)

          % Compute S_wet for wings with low tc
          function output = compute_S_wet_wing_lowtc(geometry_obj, S_exposed)
               output = 2.003*S_exposed; % Raymer, 6th ed, eq 7.11
          end

          % Compute S_wet for wings with high tc
          function output = compute_S_wet_wing_hightc(geometry_obj, S_exposed, tc)
               output = S_exposed*(1.977 + 0.52*tc);
          end
     end
end