%% ---------------------------------------------------
% Function: Show results table as a GUI element
function showResultTable(TW_table, constraintNames, Wto_S_range)
    fig = figure('Name', 'T/W Table');
    uitable(fig, ...
        'Data', round(TW_table, 3), ...
        'ColumnName', compose('W/S = %d', Wto_S_range), ...
        'RowName', constraintNames, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1]);
end