function T = showInheritedMembers(className)
% showInheritedMembers  Show properties and methods inherited by a class.
%
% Example:
%   T = showInheritedMembers("F16AeroLevel2")

    className = string(className);
    mc = meta.class.fromName(className);

    if isempty(mc)
        error("Class not found on MATLAB path: %s", className);
    end

    rows = {};

    % Properties
    for k = 1:numel(mc.PropertyList)
        p = mc.PropertyList(k);

        definingClass = string(p.DefiningClass.Name);
        isInherited = definingClass ~= className;

        rows(end+1,:) = { ...
            string(p.Name), ...
            "Property", ...
            definingClass, ...
            isInherited, ...
            string(p.GetAccess), ...
            string(p.SetAccess), ...
            p.Abstract, ...
            false ...
            }; %#ok<AGROW>
    end

    % Methods
    for k = 1:numel(mc.MethodList)
        m = mc.MethodList(k);

        definingClass = string(m.DefiningClass.Name);
        isInherited = definingClass ~= className;

        rows(end+1,:) = { ...
            string(m.Name), ...
            "Method", ...
            definingClass, ...
            isInherited, ...
            string(m.Access), ...
            "", ...
            m.Abstract, ...
            m.Static ...
            }; %#ok<AGROW>
    end

    T = cell2table(rows, ...
        "VariableNames", [ ...
            "Name", ...
            "Kind", ...
            "DefiningClass", ...
            "IsInherited", ...
            "GetAccess", ...
            "SetAccess", ...
            "IsAbstract", ...
            "IsStatic"]);

    % Optional cleanup: remove built-in handle methods if you do not care.
    T = T(T.DefiningClass ~= "handle", :);

    % Sort for readability
    T = sortrows(T, ["Kind", "DefiningClass", "Name"]);

    disp(T)
end