%% run_b777_TS_diagram
%   Boeing 777-200LR dimensional T-S sizing diagram [metabook Example 4.2,
%   §4.12, Fig. 4.7]. Builds the B777 L1 discipline stack plus the L1 mission,
%   drives src/sizing/TSDiagram.m: every (T, S) cell is a SIZED aircraft with a
%   converged TOGW [metabook Algorithm 2], constraints traced as T(S)/S(T)
%   curves [Algorithm 4], fuel-burn contours superimposed, and the actual
%   777-200LR marked.
%
%   Style/wiring follows examples/F16A/studies/run_F16_TS_diagram.m (caller owns
%   discipline construction); export follows the sanity_checks scripts (console +
%   files into the gitignored examples/B777/output/).
%
%   RELAXATION. The metabook L1 transport closure is stable from below (empty
%   weight scales with W0 via the Raymer We/W0 regression), so the default
%   relax_W0 = 0.5 converges cleanly across this grid -- no per-stack tuning is
%   needed (contrast the F-16 Brandt stack, whose steep fixed-OEW closure needs
%   0.25). Left at the default here; if a future spec change makes the grid show
%   spurious NaNs, set ts.relax_W0 lower and document it.

% Caller owns discipline construction (dependency injection). TSDiagram mutates
% the shared geom/prop/wts objects in place during the scan (see its header);
% the stack is built fresh here and used for nothing else afterwards.
sp   = b777_spec_path(1);
rp   = b777_requirements_path();
geom = B777GeomL2(sp);
prop = B777PropL1(sp);
aero = B777AeroL1(geom, sp);
tail = B777TailL1();
wts  = B777WeightsL2(sp, geom, prop);
miss = MissionAnalysisL1.from_requirements(aero, prop, geom, rp, "long_range");
con  = ConstraintAnalysis.from_requirements(aero, prop, rp, ...
    B777ConstraintSet.constraint_map(), linspace(60, 300, 241));

ts = TSDiagram(aero, prop, wts, geom, miss, con, tail);
% Default relax_W0 = 0.5 is kept (see header -- the transport closure is stable
% from below). max_iter left at the default 200.

% Uniform grids (TSDiagram.plot's feasible-region shading assumes uniform
% spacing). Ranges bracket the actual 777 (S = 4605 ft^2, T = 220000 lbf) and
% the converged design point on both sides.
S_grid = linspace(2000, 6000, 28);      % ft^2 (metabook Fig 4.7 axes)
T_grid = linspace(30000, 350000, 28);   % lbf (metabook Fig 4.7 axes)

% Actual-aircraft marker [metabook Fig. 4.7: "Actual 777-200LR (T = 220000 lb
% and S = 4605 ft2)"].
actual = struct('T', 220000, 'S', 4605, 'label', "Actual 777-200LR");

% Converged TOGW at the actual aircraft's (T, S) cell [metabook Algorithm 2],
% for the results export. Compare against the actual 766,800 lbf (expect the
% BY-DESIGN -8.6% metabook-L1 offset -- see b777_metabook_comparison.m).
W0_actual = ts.converge_W0(actual.T, actual.S);
fprintf('\nB777 T-S diagram [metabook Fig. 4.7]\n');
fprintf('  Converged W_TO at (T = %.0f lbf, S = %.0f ft^2): %.1f lbf (actual = 766800, %+.2f%%)\n', ...
    actual.T, actual.S, W0_actual, 100*(W0_actual - 766800)/766800);

% Fuel-burn/TOGW grid for the results export [metabook §4.12 objective
% contours]. The precomputed grid is passed straight into ts.plot ('grid'
% option) so the mesh is computed once.
fg = ts.fuel_grid(T_grid, S_grid);

% The diagram itself [metabook Fig. 4.7].
fig = ts.plot('S_grid', S_grid, 'T_grid', T_grid, 'actual', actual, 'grid', fg);

% ---- Exports into the gitignored output/ (sanity_checks pattern) ---------- %
outdir = fullfile(fileparts(mfilename('fullpath')), '..', 'output');
if ~exist(outdir, 'dir'), mkdir(outdir); end

exportgraphics(fig, fullfile(outdir, 'b777_TS_diagram.png'), 'Resolution', 200);

results = struct( ...
    'stack',      'B777 L1 disciplines x L1 mission (metabook Example 4.2)', ...
    'S_grid_ft2', S_grid, ...
    'T_grid_lbf', T_grid, ...
    'W0_lbf',     fg.W0, ...        % converged TOGW per (T, S) cell, NaN = infeasible
    'W_fuel_lbf', fg.W_fuel, ...    % mission fuel per (T, S) cell
    'relax_W0',   ts.relax_W0, ...
    'actual',     struct('T_lbf', actual.T, 'S_ft2', actual.S, ...
                         'label', actual.label, 'W0_converged_lbf', W0_actual, ...
                         'W_TO_actual_lbf', 766800));
fid = fopen(fullfile(outdir, 'b777_TS_diagram.json'), 'w');
fwrite(fid, jsonencode(results, 'PrettyPrint', true));
fclose(fid);

L = strings(0, 1);
L(end+1) = "# B777-200LR T-S Sizing Diagram [metabook Fig. 4.7]";
L(end+1) = "";
L(end+1) = "Generated by `studies/run_b777_TS_diagram.m` over the B777 L1 stack + L1 mission.";
L(end+1) = "Every grid point is a sized aircraft with a converged TOGW [metabook §4.12].";
L(end+1) = "";
L(end+1) = sprintf("- S grid: %.0f to %.0f ft^2 (%d points)", min(S_grid), max(S_grid), numel(S_grid));
L(end+1) = sprintf("- T grid: %.0f to %.0f lbf (%d points)", min(T_grid), max(T_grid), numel(T_grid));
L(end+1) = sprintf("- relax_W0 = %.2f (default -- transport closure stable from below)", ts.relax_W0);
L(end+1) = sprintf("- Converged W_TO at the actual-777 marker (T = %.0f, S = %.0f): %.1f lbf (actual 766,800; %+.2f%%, BY DESIGN -- see b777_metabook_comparison.m)", ...
    actual.T, actual.S, W0_actual, 100*(W0_actual - 766800)/766800);
L(end+1) = sprintf("- Infeasible/unconverged cells (NaN): %d of %d", ...
    nnz(~isfinite(fg.W0)), numel(fg.W0));
L(end+1) = "";
L(end+1) = "Figure: `b777_TS_diagram.png`. Full grids: `b777_TS_diagram.json`.";
writelines(L, fullfile(outdir, 'b777_TS_diagram.md'));

fprintf('  Infeasible/unconverged cells (NaN): %d of %d\n', nnz(~isfinite(fg.W0)), numel(fg.W0));
fprintf('\nWrote output/b777_TS_diagram.png, .json and .md\n');
