function T_all = weights_brandt_comparison()
%WEIGHTS_BRANDT_COMPARISON  F-16A Block 10/15 -- Weights vs Brandt ground truth.
%
%   NOT A TEST. No pass/fail assertions, not part of run_all_tests. A pure
%   reporting script: loads the F-16A L1/L2/L3 input JSONs plus
%   examples/F16A/f16a_requirements.json, runs the actual F16WeightsL1/L2/L3
%   methods and the WeightsL2/WeightsL3 static toolboxes, and compares against
%   the `weights` section of VnV/BrandtF16A/GroundTruth/f16a_ground_truth.json
%   -- the Brandt-DIRECT ground truth (NOT F16Baseline.m's older figures, which
%   fidelity_comparison.m uses instead).
%
%   *** INFORMATIONAL ONLY. NEVER PASS/FAIL. AND NOTHING PRODUCED HERE MAY EVER
%   *** BE USED TO BACKFILL A UNIT TEST'S EXPECTED VALUE (CLAUDE.md's two-tier
%   *** rule). The three TestWeights* files' former "OEW = 19,148 lbf [Brandt
%   *** Wt!B12]" assertions are exactly what that rule prevents: Wt!B12 is
%   *** 19,980.70 and 19,148.08 is corrections.xls, a different workbook
%   *** ~4.3 % away (review finding #14). Those assertions were deleted from the
%   *** unit tier in Phase 4 and became the headline rows of this report.
%
%   Where a quantity has multiple valid implementations (Raymer Eq. 10.10
%   uninstalled vs x1.3 vs Brandt's 0.199*T; the L2 psf buildup vs the L3
%   Sec. 15.3.1 buildup), EACH option gets its own row -- never just the
%   official one, and the REJECTED variants are reported too so the decisions
%   stay auditable.
%
%   Outputs (written to the same directory as this script):
%     weights_brandt_comparison.json  -- full table + metadata
%     weights_brandt_comparison.md    -- rendered markdown table
%
%   Specification: examples/F16A/examples/F16A/weights_brandt_comparison.m.
%   Run via `matlab -batch`, not the MCP evaluate tool: the wide-table disp
%   hang is on record.
%
%   REFERENCE SOURCES:
%     [Brandt]  S. Brandt, F-16A.xls workbook, sheet "Wt", via
%               VnV/BrandtF16A/GroundTruth/f16a_ground_truth.json [.weights].
%               Every Wt cell in that block was re-read live over Excel COM on
%               2026-07-25 (todo Sec. P4-0).
%     [Alt]     corrections.xls (Casey's revised-weight workbook), per
%               F16Baseline.m:136 -- a SECOND, DIFFERENT source, never Wt!B12.
%     [Raymer]  D.P. Raymer, Aircraft Design 7th ed., AIAA -- Table 3.1,
%               Table 15.2, Sec. 15.3.1 (Eqs. 15.1-15.24), Eq. 10.10.
%     [Roskam]  J. Roskam, Airplane Design Part I, Eq. 2.16 + Table 2.15.
%     [AE481]   AE481 metabook Sec. 7 "Fraction-Based Weight Estimates".

script_dir  = fileparts(mfilename('fullpath'));
sizing_root = fileparts(fileparts(script_dir));
gt_path     = fullfile(sizing_root, 'VnV', 'BrandtF16A', 'GroundTruth', 'f16a_ground_truth.json');
gt          = jsondecode(fileread(gt_path)).weights;

sc  = gt.structural_components;
es  = gt.engine_and_systems;
sm  = gt.summary;
di  = gt.di_reference_values;

% W_TO basis read from the ground-truth JSON, not hardcoded: Brandt Wt!B3/B38.
W_TO = sm.TOGW.value;   % 31,377 lbf

% The corrections.xls alternate, carried in the Alt column of every row that
% has one. LABELLED, because it is NOT Brandt Wt!B12.
ALT_OEW = sm.OEW.corrections_xls;   % 19,148.08

% ════════════════════════════════════════════════════════════════════════ %
%  BUILD THE FRAMEWORK OBJECTS AND RUN THE ACTUAL DISCIPLINE CODE
% ════════════════════════════════════════════════════════════════════════ %

% Weights takes geometry and propulsion by dependency injection (Phase 4):
% L2 injects F16GeomL2, L3 injects F16GeomL3, and BOTH inject F16PropL2 --
% there is no L3 propulsion tier, so the L3 rung's engine data is an L2 object.
prop = F16PropL2(f16a_spec_path(2));
g2   = F16GeomL2(f16a_spec_path(2), prop);
g3   = F16GeomL3(f16a_spec_path(3), prop);
req  = f16a_requirements_path();

w1 = F16WeightsL1(f16a_spec_path(1));
w2 = F16WeightsL2(f16a_spec_path(2), req, g2, prop);
w3 = F16WeightsL3(f16a_spec_path(3), req, g3, prop);

% ── L1: the two statistical regressions ─────────────────────────────────── %
oew_l1_raymer = w1.OEW(W_TO);                  % Raymer Tbl 3.1 power law
oew_l1_roskam = w1.compute_We_roskam(W_TO);    % Roskam Eq. 2.16 MIN bound

% ── L2: Table 15.2 psf buildup + metabook Sec. 7 fractions ─────────────── %
l2_wing = w2.weight_wing(W_TO);
l2_tail = w2.weight_tail(W_TO);
l2_fus  = w2.weight_fuselage(W_TO);
l2_lg   = w2.weight_landing_gear(W_TO);
l2_ie   = WeightsL2.weight_installed_engine(w2);   % Eq. 10.10 x 1.3 (L2-only)
l2_ale  = WeightsL2.weight_all_else_empty(w2, W_TO);
l2_str  = l2_wing + l2_tail.HT + l2_tail.VT + l2_fus;   % structural subtotal
oew_l2  = w2.OEW(W_TO);

% Engine-weight OPTIONS. Each gets its own row (Sec. G.4 sec. 4).
W_en_uninstalled = w2.W_en;         % Raymer Eq. 10.10, OFFICIAL at L3
W_en_installed   = l2_ie;           % Eq. 10.10 x 1.3, OFFICIAL at L2
W_en_brandt      = w2.W_en_brandt;  % 0.199*T_AB, ALREADY installed
W_en_brandt_x13  = 1.3 * W_en_brandt;                       % REJECTED
oew_l2_brandt_en = oew_l2 - W_en_installed + W_en_brandt;   % alternate
oew_l2_rejected  = oew_l2 - W_en_installed + W_en_brandt_x13; % REJECTED

% ── L3: Raymer Sec. 15.3.1 component buildup ───────────────────────────── %
l3_wing = w3.weight_wing(W_TO);
l3_tail = w3.weight_tail(W_TO);
l3_fus  = w3.weight_fuselage(W_TO);
l3_lg   = w3.weight_landing_gear(W_TO);
l3_eng  = w3.weight_engine_section(W_TO);
l3_sys  = w3.weight_systems(W_TO);
l3_str  = l3_wing + l3_tail.HT + l3_tail.VT + l3_fus;
oew_l3  = w3.OEW(W_TO);
l3_lg_total = l3_lg.main + l3_lg.nose;

w3.W_TO      = W_TO;                 % so the W_TO-dependent Dependents read
l3_W_l       = w3.W_l;               % 0.95 * W_TO (settled decision 4)
l3_sfc       = w3.SFC_mission;       % prop.get_TSFC at the requirements cruise

% The REJECTED L3 "x1.3" variant, reported once so decision 1 stays auditable.
% Reconstructed from the two places W_en enters the engine group: the dry-engine
% line (linear) and Eq. 15.9's W_en^0.717 -- not by editing the class.
sec_uninst = WeightsL3.engine_section(W_en_uninstalled,       w3.N_en, w3.N_z);
sec_x13    = WeightsL3.engine_section(1.3*W_en_uninstalled,   w3.N_en, w3.N_z);
oew_l3_rejected = oew_l3 + 0.3 * W_en_uninstalled * w3.N_en + (sec_x13 - sec_uninst);

% ── Sensitivity variants for the items STILL OPEN after the six decisions ── %
% Each is a fresh object with ONE input changed, so the deltas are independent.
wA = makeL3(req, prop);  wA.L_d = g3.L_duct;        oew_Ld    = wA.OEW(W_TO);
ind_Ld = wA.weight_engine_section(W_TO).induction;
wB = makeL3(req, prop);  wB.D_e = g3.D_exit;        oew_De    = wB.OEW(W_TO);
wC = makeL3(req, prop);  wC.design_mach = 2.05;     oew_M205  = wC.OEW(W_TO);
wD = makeL3(req, prop);  wD.K_d = 0;                oew_Kd0   = wD.OEW(W_TO);
ind_Kd0 = wD.weight_engine_section(W_TO).induction;
ind_base = l3_eng.induction;

% ── The NOT-MODELED gap tally ──────────────────────────────────────────── %
gap_total = sc.nacelles.value + sc.strakes.value ...
          + es.other_structure.value + es.armament_support.value;

% ════════════════════════════════════════════════════════════════════════ %
%  BUILD TABLE
% ════════════════════════════════════════════════════════════════════════ %

SRC_OEW = 'Brandt Wt!B12 (=SUM(B10:B11))';
SRC_EN  = ['Brandt Wt!B11 (=IF(Main!C29=Main!D29,''Engn(s) Old''!D11*Main!B28*Main!C29,' ...
           '''Engn(s) Old''!D22*Main!B28*Main!D29)); 0.199 literal at ''Engn(s)''!D22'];

T = table();

% ─────────────────────────────── SECTION 1 ─────────────────────────────── %
T = [T; srow('[1. OPERATING EMPTY WEIGHT -- THE HEADLINE. Expected = Brandt Wt!B12 = 19,980.70; Alt = corrections.xls 19,148.08]')];

T = [T; grow('OEW, Raymer Tbl 3.1 regression [lbf]', 'L1', oew_l1_raymer, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['Statistical empty-weight power law We/Wto = Kvs*A*W_TO^C, A = 2.34 / C = -0.13 ' ...
     '[metabook_data.md:22]. A CENTRAL regression through historical fighters, so a few ' ...
     'percent is the expected accuracy -- and it happens to land closest to Brandt of ' ...
     'anything in this report.'], ALT_OEW)];

T = [T; grow('OEW, Roskam Eq. 2.16 MINIMUM bound [lbf]', 'L1', oew_l1_roskam, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['DIFFERENT KIND OF QUANTITY: a LOWER BOUND (the historical efficiency frontier), not a ' ...
     'central estimate. Any real OEW must sit ABOVE it, so a negative %Diff is the CORRECT ' ...
     'result and its magnitude is not an error measure. Never summed into OEW.'], ALT_OEW, 'DEFINITIONAL')];

T = [T; grow('OEW, Tbl 15.2 psf buildup + Raymer W_en [lbf]', 'L2', oew_l2, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['OFFICIAL L2. wing 9 / HT 4 / VT 5.3 psf on EXPOSED planform + fuselage 4.8 psf on WETTED ' ...
     'area [Raymer Tbl 15.2] + LG 0.033*W_TO, installed engine 1.3 x bare, all-else 0.17*W_TO ' ...
     '[AE481 metabook Sec. 7]. Of the gap to Brandt, 2733.68 lbf (13.68 % of Wt!B12) is Brandt ' ...
     'components with NO framework analog -- see section 5.'], ALT_OEW)];

T = [T; grow('OEW, Tbl 15.2 psf buildup + Brandt W_en alt [lbf]', 'L2', oew_l2_brandt_en, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['Same buildup with Brandt''s own already-installed 0.199*T_AB engine weight substituted ' ...
     '(NO x1.3). A different engine-model FAMILY, so the framework is expected to differ; ' ...
     'reported because engine weight is the single largest divergence at L2.'], ALT_OEW, 'BY DESIGN')];

T = [T; grow('OEW, Tbl 15.2 psf + Brandt W_en x1.3 -- REJECTED [lbf]', '--', oew_l2_rejected, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['REJECTED VARIANT, reported so the decision is auditable. Applies the metabook''s x1.3 to a ' ...
     'formula readme_wt.md:230 states IS ALREADY the installed-engine weight, i.e. it installs ' ...
     'twice. It agrees BEST with Brandt of every L2 option, and that is precisely why it is ' ...
     'rejected: agreement produced by a double-counted factor is not agreement. Not a candidate.'], ...
     ALT_OEW, 'DEFINITIONAL')];

T = [T; grow('OEW, Raymer Sec. 15.3.1 buildup [lbf]', 'L3', oew_l3, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['OFFICIAL L3, at the settled decisions: UNINSTALLED W_en (no x1.3), W_l = 0.95*W_TO, ' ...
     'SFC_mission by DI at the requirements cruise point. Eqs. 15.1-15.24 group mass differently ' ...
     'from Brandt''s psf model, and the same 2733.68 lbf of unmodelled Brandt components applies.'], ...
     ALT_OEW)];

T = [T; grow('OEW, Sec. 15.3.1 with W_en x1.3 -- REJECTED [lbf]', '--', oew_l3_rejected, sm.OEW.value, SRC_OEW, '%.2f', ...
    ['REJECTED VARIANT, reported so decision 1 is auditable. It is CLOSER to Brandt than the ' ...
     'settled answer, because it double-counts the installation hardware Eqs. 15.7-15.15 already ' ...
     'supply item by item. The better agreement was the evidence AGAINST x1.3, not for it. ' ...
     'x1.3 is L2-only, and L2 has no buildup.'], ALT_OEW, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 2 ─────────────────────────────── %
T = [T; srow('[2. STRUCTURAL LINE ITEMS -- Brandt Wt!C9:H9. His psf coefficients are Wt!C7:H7 (wing 6.75 / fus 5.0 / pitch 6.0 / VT 6.0), NOT Raymer Tbl 15.2''s]')];

T = [T; grow('Wing [Tbl 15.2 psf] [lbf]', 'L2', l2_wing, sc.wing.value, 'Brandt Wt!C9', '%.2f', ...
    ['Framework: 9.0 psf x EXPOSED planform 196.2261 ft^2 [Raymer Tbl 15.2, metabook_data.md:321]. ' ...
     'Brandt: 6.75 psf x S_ref with AR^1.8, n_ult^0.2, tc^-0.7 and 1/cos(Lambda) factors -- a ' ...
     'psf model like ours but a different coefficient AND different correction factors.'], ...
     sc.wing.corrections_xls)];

T = [T; grow('Wing [Eq. 15.1] [lbf]', 'L3', l3_wing, sc.wing.value, 'Brandt Wt!C9', '%.2f', ...
    ['Raymer Eq. 15.1 statistical buildup. Reads ~34 % above Brandt: Raymer''s fighter-wing ' ...
     'regression is fitted across production aircraft and does not capture the F-16''s unusually ' ...
     'light, highly optimised wing. Raymer states these are estimates with intrinsic scatter. ' ...
     'Every Eq. 15.1 exponent is an OPEN verify-against-book item (todo Sec. 3a).'], ...
     sc.wing.corrections_xls)];

T = [T; grow('Fuselage [Tbl 15.2 psf] [lbf]', 'L2', l2_fus, sc.fuselage.value, 'Brandt Wt!D9', '%.2f', ...
    ['Framework: 4.8 psf x WETTED area 730.3023 ft^2 [Raymer Tbl 15.2, metabook_data.md:324; area ' ...
     'via Roskam Vol. II Eq. 12.3]. Brandt: 5.0 psf x his own S_wet_fuse 730.422 x a fineness ' ...
     'factor -- nearly the same area, so this row isolates the psf coefficient difference.'], ...
     sc.fuselage.corrections_xls)];

T = [T; grow('Fuselage [Eq. 15.4] [lbf]', 'L3', l3_fus, sc.fuselage.value, 'Brandt Wt!D9', '%.2f', ...
    ['Raymer Eq. 15.4, on the 47.5 ft T.O. length and the 5.0 ft maximum structural DEPTH. ' ...
     '! D_fus here is NOT geom.D_fus = 6.0 (the Roskam equivalent diameter): Eq. 15.4 carries ' ...
     'D_fus^0.849, so that substitution would inflate this row by +17.9 % silently.'], ...
     sc.fuselage.corrections_xls)];

T = [T; grow('Pitch control / HT [Tbl 15.2 psf] [lbf]', 'L2', l2_tail.HT, sc.pitch_control_HT.value, 'Brandt Wt!E9', '%.2f', ...
    ['DIFFERENT AREA CONVENTION, not an agreement check. Brandt Wt!E9 = 6.0 x Main!C18 = 6.0 x 108, ' ...
     'the FULL planform; the framework uses the EXPOSED planform per Raymer Tbl 15.2''s own ' ...
     'definition (49.8473 ft^2 at L2). The Alt column''s 199.39 is close only because ' ...
     'corrections.xls happens to land near 4.0 x exposed.'], ...
     sc.pitch_control_HT.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Pitch control / HT [Eq. 15.2] [lbf]', 'L3', l3_tail.HT, sc.pitch_control_HT.value, 'Brandt Wt!E9', '%.2f', ...
    ['Same FULL-vs-EXPOSED definitional split as the L2 row. Raymer Eq. 15.2 on the EXPOSED ' ...
     '51.1486 ft^2, which is +2.605 % above L2''s 49.8473 because F16GeomL3 takes the physical ' ...
     '18.5 ft HT span as primary (F16GeomL3.md §4) -- itself BY DESIGN, not error.'], ...
     sc.pitch_control_HT.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Vertical tail [Tbl 15.2 psf] [lbf]', 'L2', l2_tail.VT, sc.vertical_tail.value, 'Brandt Wt!F9', '%.2f', ...
    ['DIFFERENT AREA CONVENTION. Brandt Wt!F9 = 6.0 x Main!H18 = 6.0 x 60, the FULL planform; ' ...
     'the framework uses the EXPOSED 40.8897 ft^2 x 5.3 psf [metabook_data.md:323].'], ...
     sc.vertical_tail.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Vertical tail [Eq. 15.3] [lbf]', 'L3', l3_tail.VT, sc.vertical_tail.value, 'Brandt Wt!F9', '%.2f', ...
    ['Same FULL-vs-EXPOSED split. Raymer Eq. 15.3 on the EXPOSED planform SET -- S_vt 40.8897, ' ...
     'AR_vt 1.294, lambda_vt 0.437 -- NOT the FULL 60 / 1.6 / 0.5. Eq. 15.3 also carries a ' ...
     'documented code-vs-extract exponent CONFLICT on cos(Lambda_vt) (todo Sec. 3a row 2).'], ...
     sc.vertical_tail.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Nacelles -- NOT MODELED [lbf]', 'N/A', NaN, sc.nacelles.value, 'Brandt Wt!G9', '%.2f', ...
    ['No framework nacelle-weight component exists at any fidelity level. Brandt: 4.5 psf x his ' ...
     'half-buried nacelle area (Geom!B4). Counted in the section-5 gap tally.'], ...
     sc.nacelles.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Strakes -- NOT MODELED [lbf]', 'N/A', NaN, sc.strakes.value, 'Brandt Wt!H9', '%.2f', ...
    ['No framework strake component exists -- the same gap the geometry report records for strake ' ...
     'wetted/exposed area. Brandt: 4.5 psf x 20 ft^2. Counted in the section-5 gap tally.'], ...
     sc.strakes.corrections_xls, 'DEFINITIONAL')];

T = [T; grow('Structural subtotal, Tbl 15.2 (wing+fus+HT+VT) [lbf]', 'L2', l2_str, sc.structural_subtotal.value, 'Brandt Wt!B9', '%.2f', ...
    ['NOT LIKE-FOR-LIKE: Brandt''s Wt!B9 = SUM(C9:H9) also contains nacelles (186.82) and strakes ' ...
     '(90.00), for which the framework has no analog, and two of the four shared items use his ' ...
     'FULL-planform tail areas. Group-level agreement is not meaningful here.'], NaN, 'DEFINITIONAL')];

T = [T; grow('Structural subtotal, Eqs. 15.1-15.4 (wing+fus+HT+VT) [lbf]', 'L3', l3_str, sc.structural_subtotal.value, 'Brandt Wt!B9', '%.2f', ...
    'Same non-like-for-like subtotal as the L2 row, over the Sec. 15.3.1 components.', ...
    NaN, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 3 ─────────────────────────────── %
T = [T; srow('[3. ENGINE + SYSTEMS -- Brandt Wt!B22:B31. His fraction literals are Wt!F23:F31, live-verified 2026-07-25]')];

T = [T; grow('Landing gear, total [lbf]', 'L2', l2_lg, es.landing_gear.value, 'Brandt Wt!B23 (=B8 = B3*F23)', '%.2f', ...
    ['SAME MODEL FAMILY, different coefficient: framework 0.033*W_TO [AE481 metabook Sec. 7, ' ...
     'metabook_data.md:330] vs Brandt 0.034*W_TO (Wt!F23 = 0.034, a bare literal). LOCKED decision ' ...
     '(user 2026-07-24): use 0.033. The -2.94 % is exactly 0.033/0.034 - 1, i.e. entirely the ' ...
     'coefficient choice.'], NaN, 'BY DESIGN')];

T = [T; grow('Landing gear, main only (Eq. 15.5) [lbf]', 'L3', l3_lg.main, NaN, 'no single Brandt cell', '%.2f', ...
    ['Brandt carries ONE gear line; the framework splits main (Eq. 15.5) and nose (Eq. 15.6), so ' ...
     'only the total below compares. Reported for the breakdown. L_m is converted feet->INCHES ' ...
     'per Raymer''s nomenclature; omitting that made the gear ~11x too light.'], NaN, 'DEFINITIONAL')];

T = [T; grow('Landing gear, nose only (Eq. 15.6) [lbf]', 'L3', l3_lg.nose, NaN, 'no single Brandt cell', '%.2f', ...
    'See the main-gear row: Brandt has no nose/main split.', NaN, 'DEFINITIONAL')];

T = [T; grow('Landing gear, total (Eqs. 15.5+15.6) [lbf]', 'L3', l3_lg_total, es.landing_gear.value, 'Brandt Wt!B23', '%.2f', ...
    ['A statistical strut-sizing buildup vs Brandt''s 0.034*W_TO fraction -- different formula ' ...
     'families, and they agree to within ~9 %. Was 1057.27 (-0.9 %) before Phase 4, on a FROZEN ' ...
     'W_l = 20681 [Brandt Wt!B41] that made the entire gear group insensitive to gross weight ' ...
     '(todo Sec. P4-17). The apparently better old agreement came from a dead computation.'], ...
     NaN, 'BY DESIGN')];

T = [T; grow('Air induction / inlet duct (Eq. 15.10) [lbf]', 'L3', ind_base, es.inlet_duct.value, 'Brandt Wt!B24 (=B20*F24)', '%.2f', ...
    ['Different formula families: Raymer Eq. 15.10 on duct geometry (L_d, L_s, D_e) vs Brandt''s ' ...
     '3.9 x W_nacelles -- and the framework has no nacelle weight at all, so his basis does not ' ...
     'even exist here. Eq. 15.10 is the WEAKEST-SOURCED equation in WeightsL3: three of its terms ' ...
     'are FROM-CODE, absent from the repo extract (todo Sec. 3a rows 3-7).'], NaN, 'BY DESIGN')];

T = [T; grow('Flight controls (Eq. 15.17) [lbf]', 'L3', l3_sys.flight_ctrl, es.flight_controls.value, 'Brandt Wt!B25', '%.2f', ...
    ['Raymer Eq. 15.17 on M, S_cs, N_s, N_c vs Brandt''s 0.012*W_TO + a LE-flap area term. ' ...
     'Different families. S_cs = 190 ft^2 is an unpinned geometry estimate, and N_c^0.127 is ' ...
     'FROM-CODE (todo Sec. 3a rows 10-13).'], NaN, 'BY DESIGN')];

T = [T; grow('Electrical (Eq. 15.20) [lbf]', 'L3', l3_sys.electrical, es.electrical.value, 'Brandt Wt!B26', '%.2f', ...
    ['Raymer Eq. 15.20 on R_kva, L_a, N_gen vs Brandt''s 0.017*W_TO. R_kva = 80 and L_a = 10 ft ' ...
     'are unpinned estimates, so this row''s agreement is partly a property of those guesses.'], ...
     NaN, 'BY DESIGN')];

T = [T; grow('Hydraulics (Eq. 15.19) [lbf]', 'L3', l3_sys.hydraulics, es.hydraulics.value, 'Brandt Wt!B27', '%.2f', ...
    ['Raymer Eq. 15.19 = 37.23*K_vsh*N_u^0.664 vs Brandt''s 0.0117*W_TO. N_u = 5 is an unpinned ' ...
     'estimate and the equation is very sensitive to it, which is the likely bulk of the gap.'], ...
     NaN, 'BY DESIGN')];

T = [T; grow('ECS / AC + anti-ice (Eq. 15.23) [lbf]', 'L3', l3_sys.ac_antiice, es.ecs_ac_antiice.value, 'Brandt Wt!B28', '%.2f', ...
    ['Raymer Eq. 15.23 on the avionics weight and crew count vs Brandt''s 0.0115*W_TO.'], ...
     NaN, 'BY DESIGN')];

T = [T; grow('Avionics (Eq. 15.21) [lbf]', 'L3', l3_sys.avionics, es.avionics.value, 'Brandt Wt!B30', '%.2f', ...
    ['Raymer Eq. 15.21 = 2.117*W_uav^0.933 vs Brandt''s 0.081*W_TO. W_uav = 1500 lbf is an ' ...
     'UNPINNED estimate for the Block 10 suite, and it is the only input -- so this row is really ' ...
     'a statement about that estimate, not about the equation.'], NaN, 'BY DESIGN')];

T = [T; grow('Fuel system (Eq. 15.16) [lbf]', 'L3', l3_sys.fuel_sys, NaN, 'no Brandt cell', '%.2f', ...
    ['Brandt does not tabulate a fuel-system line. Reported because it is the ONLY consumer of ' ...
     'SFC_mission (see section 4b): moving SFC from Brandt''s 0.70 to the framework''s cruise ' ...
     '1.0071 (+43.87 %) moves this component only +9.48 %, since Eq. 15.16 carries ' ...
     '((T*SFC)/1000)^0.249. V_t = 940 gal rests on an UNCITED 6.7 lb/gal density (todo Sec. P4-5b).'], ...
     NaN, 'DEFINITIONAL')];

T = [T; grow('Other structure -- NOT MODELED [lbf]', 'N/A', NaN, es.other_structure.value, 'Brandt Wt!B29 (=B9*F29)', '%.2f', ...
    ['A LUMPED 0.30 x W_structure catch-all with no single framework analog -- whatever it covers ' ...
     'is distributed across the framework''s named components, or missing. The largest single ' ...
     'unmodelled item, 10.09 % of Wt!B12. Counted in the section-5 tally.'], NaN, 'DEFINITIONAL')];

T = [T; grow('Armament support -- NOT MODELED [lbf]', 'N/A', NaN, es.armament_support.value, 'Brandt Wt!B31', '%.2f', ...
    ['No framework analog. Brandt: 0.10 x expendable payload = 0.10 x 4400. Counted in the ' ...
     'section-5 tally.'], NaN, 'DEFINITIONAL')];

T = [T; grow('Airframe (structure + systems, engine excluded) [lbf]', 'L3', oew_l3 - l3_eng.total, sm.airframe.value, 'Brandt Wt!B10 (=B9+SUM(B23:B31))', '%.2f', ...
    ['L3 OEW less the whole engine GROUP. Not like-for-like: Brandt''s B10 excludes only his single ' ...
     'engine line (B11), while the framework''s engine group also contains the Eqs. 15.7-15.15 ' ...
     'installation hardware, some of which Brandt books under other headings.'], NaN, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 4 ─────────────────────────────── %
T = [T; srow('[4. ENGINE WEIGHT -- RAYMER vs BRANDT. Brandt Wt!B11/B22 = 0.199*T_AB_SLS is ALREADY INSTALLED (readme_wt.md:230), which is what makes the first row definitional]')];

T = [T; grow('W_en UNINSTALLED [Raymer Eq. 10.10] -- OFFICIAL at L3 [lbf]', 'L3', W_en_uninstalled, es.engine.value, SRC_EN, '%.4f', ...
    ['DIFFERENT KIND OF QUANTITY: uninstalled vs Brandt''s already-installed figure, so the %Diff ' ...
     'is not an error measure. This is the value L3 consumes (settled decision 1): Sec. 15.3.1 ' ...
     'adds mounts (15.7), firewall (15.8), section (15.9), induction (15.10), tailpipe (15.11), ' ...
     'cooling (15.12), oil (15.13), controls (15.14) and starter (15.15) separately. ' ...
     'W = 0.0637*T^1.1*M^0.25*exp(-0.81*BPR) at T = 23770, M = 2.0, BPR = 0.71 ' ...
     '[raymer_data.md:38].'], NaN, 'DEFINITIONAL')];

T = [T; grow('W_installed_engine [Eq. 10.10 x 1.3] -- OFFICIAL at L2 [lbf]', 'L2', W_en_installed, es.engine.value, SRC_EN, '%.4f', ...
    ['LIKE-FOR-LIKE: both sides are installed engine weights. The x1.3 installed/bare factor ' ...
     '[AE481 metabook Sec. 7, metabook_data.md:333] is L2-ONLY -- L2 has no installation buildup, ' ...
     'so one lumped factor is the right model there and only there. This is the genuine agreement ' ...
     'check of the four rows in this section.'], NaN)];

T = [T; grow('W_en [Brandt 0.199*T_AB alternate, NO x1.3] [lbf]', 'L2/L3', W_en_brandt, es.engine.value, SRC_EN, '%.4f', ...
    ['EXACT BY CONSTRUCTION -- it IS Brandt''s own formula fed Brandt''s own thrust. Kept as a ' ...
     'POSITIVE CONTROL that the propulsion DI delivers T_SL = 23,770 lbf correctly; a nonzero ' ...
     '%Diff here would mean the injected thrust is wrong. Brandt''s 0.199 is never ported into a ' ...
     'framework equation.'], NaN, 'BY DESIGN')];

T = [T; grow('W_en [Brandt 0.199*T x 1.3 -- REJECTED] [lbf]', '--', W_en_brandt_x13, es.engine.value, SRC_EN, '%.4f', ...
    ['REJECTED, reported once and labelled. Double-applies an installation factor Brandt has ' ...
     'already applied (readme_wt.md:230 states 0.199*T_AB IS the installed-engine formula). The ' ...
     'resulting L2 OEW agrees best with Wt!B12 of any option, which is the reason to reject it.'], ...
     NaN, 'DEFINITIONAL')];

T = [T; grow('Engine group total (dry + Eqs. 15.7-15.15) [lbf]', 'L3', l3_eng.total, es.engine.value, 'Brandt Wt!B11/B22', '%.2f', ...
    ['NOT like-for-like: this is the whole installed propulsion GROUP built item by item, while ' ...
     'Brandt''s B11 is one 0.199*T line and he books the inlet duct separately at B24. The nearer ' ...
     'comparison is (framework engine group) vs (Brandt B11 + B24 = 5458.82), i.e. still a ' ...
     'different partition of the same hardware.'], NaN, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 4b ────────────────────────────── %
T = [T; srow('[4b. THE TWO DEPENDENCY-INJECTED SCALARS -- both DEFINITIONAL by settled decision, not errors to chase]')];

T = [T; grow('SFC_mission [prop.get_TSFC @ 36 kft / M 0.87] [1/hr]', 'L3', l3_sfc, di.SFC_mission_per_hr.value, 'Brandt Main!C30', '%.6f', ...
    ['+43.9 %, ACCEPTED BY DECISION 2. Two deliberate, independent causes: (a) CONDITION -- a real ' ...
     'cruise point from f16a_requirements.json vs Brandt''s single stored SLS constant; ' ...
     '(b) INSTALLATION BASIS -- get_TSFC returns the UNINSTALLED mil TSFC, Brandt''s 0.70 is ' ...
     'already installed (do not double-apply the 1.08). One consistency point in the framework''s ' ...
     'favour: Brandt''s own Consts! cruise row is pct_AB = 0, i.e. dry/mil, and get_TSFC resolves ' ...
     'to the mil path there -- the POWER SETTING matches. ! The Phase-3 claim that get_TSFC ' ...
     '"duplicates" 0.70 was FALSE: it returns 0.70 at no condition (todo Sec. P4-15).'], ...
     NaN, 'DEFINITIONAL')];

T = [T; grow('W_l landing design gross weight [0.95*W_TO] [lbf]', 'L3', l3_W_l, sm.landing_weight.value, 'Brandt Wt!B41 (=SUM(B16:B32))', '%.2f', ...
    ['+44.1 %, and the two are DEFINITIONALLY different quantities: a design landing-weight rule ' ...
     'of thumb vs a back-calculated subtotal of Brandt''s OWN weight statement. Brandt''s exact ' ...
     'decomposition is W_TO - fuel - expendable stores = 31377.000000 - 6296.299422 - 4400 = ' ...
     '20680.700578, i.e. an implied ratio of 0.6591, not 0.95. ! THE 0.95 FACTOR HAS NO CITATION ' ...
     'ANYWHERE IN THIS REPO -- user-supplied, todo Sec. P4-16 OPEN. It replaced a FROZEN ' ...
     'W_l = 20681 that made the whole gear group insensitive to gross weight (Sec. P4-17).'], ...
     NaN, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 5 ─────────────────────────────── %
T = [T; srow('[5. NOT-MODELED GAP TALLY -- Brandt components with no framework analog at any fidelity level]')];

T = [T; grow('NOT MODELED total (nacelles+strakes+other structure+armament) [lbf]', 'N/A', NaN, gap_total, ...
    'Brandt Wt!G9 + H9 + B29 + B31', '%.2f', ...
    sprintf(['%.2f + %.2f + %.2f + %.2f = %.2f lbf = %.2f %% of Brandt Wt!B12. This is the single ' ...
     'largest identified contributor to every OEW row''s negative %%Diff in section 1, and it is ' ...
     'a MISSING-COMPONENT gap, not an equation error. Mirrors the geometry report''s strake-gap ' ...
     'treatment (todo 2026-07-25 Sec. 23).'], ...
     sc.nacelles.value, sc.strakes.value, es.other_structure.value, es.armament_support.value, ...
     gap_total, 100*gap_total/sm.OEW.value), NaN, 'DEFINITIONAL')];

% ─────────────────────────────── SECTION 6 ─────────────────────────────── %
T = [T; srow('[6. SENSITIVITY TO THE ITEMS STILL OPEN AFTER THE 2026-07-25 DECISIONS -- Brandt = N/A, each applied ALONE on the settled L3 OEW base]')];

T = [T; grow(sprintf('OEW with L_d <- geom.L_duct (%.1f -> %.1f ft) [lbf]', w3.L_d, g3.L_duct), ...
    'L3', oew_Ld, NaN, 'todo Sec. P4-4 (OPEN)', '%.2f', ...
    sprintf(['A CITED geometry analog exists (geom.L_duct = %.1f ft [Brandt Main!F32]) for what is ' ...
     'currently an unpinned %.1f ft estimate. Wiring it moves Eq. 15.10 air induction ' ...
     '%.2f -> %.2f lbf (+%.1f %%) and OEW by %+.2f lbf. Deliberately NOT wired this phase -- ' ...
     'user decision required.'], g3.L_duct, w3.L_d, ind_base, ind_Ld, ...
     100*(ind_Ld-ind_base)/ind_base, oew_Ld - oew_l3), NaN, 'DEFINITIONAL')];

T = [T; grow(sprintf('OEW with D_e <- geom.D_exit (%.2f -> %.6f ft) [lbf]', w3.D_e, g3.D_exit), ...
    'L3', oew_De, NaN, 'todo Sec. P4-4 (OPEN)', '%.2f', ...
    sprintf(['Same open question for the engine exit diameter: a cited geometry analog ' ...
     '(geom.D_exit = %.6f ft, itself sqrt(T_AB_SLS/1900)) vs an unpinned ~40 in estimate. D_e ' ...
     'enters Eqs. 15.10, 15.11 and 15.12, total OEW effect %+.2f lbf.'], ...
     g3.D_exit, oew_De - oew_l3), NaN, 'DEFINITIONAL')];

T = [T; grow('OEW with design_mach <- T.O. limit (2.0 -> 2.05) [lbf]', 'L3', oew_M205, NaN, ...
    'todo Sec. P4-13 (a CITATION question)', '%.2f', ...
    sprintf(['design_mach = 2.0 is BRANDT''s Main! aircraft.Mmax [GroundTruth/f16a_geometry.json:9]. ' ...
     'The T.O. 1F-16A-1 operating Mach LIMIT is a DIFFERENT number, 2.05 ' ...
     '[f16a_ground_truth.json:228]. Citing 2.0 to the T.O. would attribute a Brandt input to a ' ...
     'primary document that says otherwise -- the same class of error as 19,148-cited-as-Wt!B12. ' ...
     'The VALUE barely matters (%+.2f lbf on OEW via Eq. 10.10 M^0.25, Eq. 15.3 M^0.341 and ' ...
     'Eq. 15.17 M^0.003), which is exactly why the citation must not drift unnoticed.'], ...
     oew_M205 - oew_l3), NaN, 'DEFINITIONAL')];

T = [T; grow('OEW with K_d = 0 (legal STRAIGHT-DUCT input) [lbf]', 'L3', oew_Kd0, NaN, ...
    'todo Sec. P4-11 (OPEN, unguarded by decision 6)', '%.2f', ...
    sprintf(['! THE ONLY PLACE THIS SILENT ZERO IS VISIBLE ANYWHERE. K_d = 0 is documented in ' ...
     'WeightsL3.air_induction as the legitimate straight-duct value, and 0^0.182 = 0, so a legal ' ...
     'documented input SILENTLY ZEROES the entire Eq. 15.10 air-induction component: ' ...
     '%.2f -> %.4f lbf, OEW %.2f -> %.2f (%+.2f). No error, no warning, not even a NaN. ' ...
     'NO GUARD IS ADDED, by explicit user decision 6, and there is deliberately NO unit test for ' ...
     'this either -- testing unguarded behaviour would manufacture a false green. COROLLARY: if ' ...
     'K_d = 0 is legal then the code''s K_d cannot be Raymer''s multiplicative base, because a ' ...
     'straight duct does not weigh nothing, so the term''s exponent or placement is itself ' ...
     'suspect (todo Sec. 3a row 7). A guard alone would mask that.'], ...
     ind_base, ind_Kd0, oew_l3, oew_Kd0, oew_Kd0 - oew_l3), NaN, 'DEFINITIONAL')];

% ════════════════════════════════════════════════════════════════════════ %
%  DISPLAY
% ════════════════════════════════════════════════════════════════════════ %

now_str = char(datetime('now', 'Format', 'yyyy-MM-dd'));
BAR     = repmat('=', 1, 110);

fprintf('\n%s\n', BAR);
fprintf('  F-16A BLOCK 10/15 -- WEIGHTS vs BRANDT GROUND TRUTH\n');
fprintf('  W_TO = %.0f lbf [Brandt Wt!B3 = Main!O15]  |  Generated %s\n', W_TO, now_str);
fprintf('  Source: VnV/BrandtF16A/GroundTruth/f16a_ground_truth.json [.weights] (Brandt-direct,\n');
fprintf('          every Wt cell live-read over Excel COM 2026-07-25; NOT F16Baseline.m)\n');
fprintf('  INFORMATIONAL ONLY -- never pass/fail, and never a source for a unit test''s expected value.\n');
fprintf('%s\n\n', BAR);

disp(T);

fprintf('  NOTES\n');
fprintf('  (a) Brandt''s structural line items use a psf x area model with HIS OWN coefficients\n');
fprintf('      (Wt!C7:H7 = wing 6.75 / fuselage 5.0 / pitch 6.0 / VT 6.0 / nacelle 4.5 / strake 4.5\n');
fprintf('      lbf/ft^2). The framework''s L2 is also psf x area but with RAYMER TABLE 15.2''s\n');
fprintf('      coefficients (9 / 4.8 / 4 / 5.3), and L3 is the Raymer Sec. 15.3.1 statistical\n');
fprintf('      buildup, which groups mass differently again. Per-component agreement is NOT expected.\n');
fprintf('  (b) Brandt''s TAIL line items use the FULL planform areas (Wt!E9 = 6.0 x 108,\n');
fprintf('      Wt!F9 = 6.0 x 60); the framework uses the EXPOSED areas per Raymer Table 15.2''s own\n');
fprintf('      definition (49.8473 / 40.8897 at L2, 51.1486 / 40.8897 at L3). Those rows are\n');
fprintf('      DEFINITIONAL, not BY DESIGN -- the two sides are different kinds of area.\n');
fprintf('  (c) THE EXPECTED OEW IS Wt!B12 = %.2f lbf. The Alt column''s %.2f is\n', ...
    sm.OEW.value, ALT_OEW);
fprintf('      corrections.xls Wt!B12 (Casey''s revised-weight workbook), NOT the original Wt!B12 --\n');
fprintf('      two distinct provenances %.2f %% apart. The unit tests used to assert the %.0f\n', ...
    100*(ALT_OEW - sm.OEW.value)/sm.OEW.value, ALT_OEW);
fprintf('      figure while CITING Wt!B12 (review finding #14); that assertion has been deleted from\n');
fprintf('      the unit tier and lives here instead.\n');
fprintf('  (d) %.2f lbf of Brandt''s weight statement (%.2f %% of Wt!B12) has NO framework analog at\n', ...
    gap_total, 100*gap_total/sm.OEW.value);
fprintf('      any fidelity level: nacelles %.2f + strakes %.2f + lumped "other structure" %.2f\n', ...
    sc.nacelles.value, sc.strakes.value, es.other_structure.value);
fprintf('      + armament support %.2f. That is a MISSING-COMPONENT gap, not an equation error, and\n', ...
    es.armament_support.value);
fprintf('      it accounts for the bulk of every negative OEW %%Diff in section 1.\n');
fprintf('  (e) Section 6''s K_d = 0 row is the ONLY place the unguarded silent-zero of the 227.54 lbf\n');
fprintf('      air-induction component is visible. Decision 6 left it unguarded on purpose and no\n');
fprintf('      unit test asserts it, so this report is its sole record. todo Sec. P4-11 stays OPEN.\n');
fprintf('\n%s\n\n', BAR);

% ════════════════════════════════════════════════════════════════════════ %
%  EXPORT
% ════════════════════════════════════════════════════════════════════════ %

out_json = fullfile(script_dir, 'weights_brandt_comparison.json');
out_md   = fullfile(script_dir, 'weights_brandt_comparison.md');

data.generated = now_str;
data.aircraft  = 'F-16A Block 10/15';
data.W_TO_lbf  = W_TO;
data.source    = 'VnV/BrandtF16A/GroundTruth/f16a_ground_truth.json [.weights]';
data.alt_source = sprintf(['corrections.xls Wt!B12 (Casey''s revised-weight workbook) = %.2f -- ' ...
    'NOT the original Brandt Wt!B12 = %.2f'], ALT_OEW, sm.OEW.value);
data.rows      = table_to_rows(T);

fid = fopen(out_json, 'w');
fprintf(fid, '%s', jsonencode(data, 'PrettyPrint', true));
fclose(fid);
fprintf('  JSON     -> %s\n', out_json);

write_markdown(T, out_md, W_TO, now_str, sm.OEW.value, ALT_OEW, gap_total);
fprintf('  Markdown -> %s\n\n', out_md);

T_all = T;

end

% ─── local helpers ───────────────────────────────────────────────────── %

function w = makeL3(req, prop)
%MAKEL3  A FRESH F16WeightsL3 (and a fresh geometry) for a sensitivity variant.
%   Fresh objects so that mutating one input for a sensitivity row cannot leak
%   into any other row -- F16GeomL3 and F16PropL2 are handle classes.
    w = F16WeightsL3(f16a_spec_path(3), req, ...
                     F16GeomL3(f16a_spec_path(3), prop), prop);
end

function T = grow(name, fidelity, computed, expected, src, numfmt, notes, alt_value, divergence)
%GROW  One comparison row.
%   Columns: Fidelity / Computed / Brandt / PctDiff / Alt / Divergence / Source / Notes.
%
%   fidelity   — which weights tier produced `computed` ('L1'/'L2'/'L3'), 'L2/L3' for a
%                quantity both tiers share, '--' for a REJECTED variant no tier ships, or
%                'N/A' for a Brandt quantity nothing models (Computed is NaN in that case).
%   alt_value  — OPTIONAL SECOND SOURCE: the corrections.xls figure where one exists.
%                NaN or omitted -> 'N/A'. This is the geometry report's `TO` column,
%                renamed because the second source here is a WORKBOOK, not the T.O.
%                ★ It carries corrections.xls Wt!* (Casey's revised-weight workbook), which
%                is NOT the original Brandt Wt!* -- conflating the two is review finding
%                #14, the reason the OEW check left the unit tier.
%   divergence — OPTIONAL annotation, three states:
%                'BY DESIGN'    — the SAME KIND of quantity as Brandt's, but the framework is
%                                 expected to differ: a different formula family, or a locked
%                                 decision to use a different coefficient (e.g. LG 0.033 vs
%                                 Brandt's 0.034). The %Diff IS meaningful and should be
%                                 small-ish -- sanity-check its magnitude.
%                'DEFINITIONAL' — a DIFFERENT KIND of quantity altogether (e.g. the
%                                 uninstalled Eq. 10.10 W_en against Brandt's already-installed
%                                 0.199*T; the Roskam MINIMUM bound against a central estimate;
%                                 EXPOSED vs FULL tail areas; a design landing-weight rule
%                                 against a back-calculated weight-statement subtotal). The
%                                 %Diff is NOT a meaningful error measure at all -- do not
%                                 chase it.
%                blank          — a genuine agreement check; a large %Diff here IS worth
%                                 chasing.
%
%   This report is INFORMATIONAL ONLY -- never pass/fail, and never a source for a unit
%   test's expected value (CLAUDE.md's two-tier rule).
    if nargin < 7; notes      = '';  end
    if nargin < 8; alt_value  = NaN; end
    if nargin < 9; divergence = '';  end
    if isnan(computed)
        comp_s = 'N/A';
    else
        comp_s = sprintf(numfmt, computed);
    end
    if isnan(expected)
        exp_s = 'N/A';
        err_s = ' - ';
    else
        exp_s = sprintf(numfmt, expected);
        if isnan(computed)
            err_s = ' - ';
        elseif expected ~= 0
            err_s = sprintf('%+.2f%%', 100*(computed - expected)/expected);
        else
            err_s = 'N/A';
        end
    end
    if isnan(alt_value)
        alt_s = 'N/A';
    else
        alt_s = sprintf(numfmt, alt_value);
    end
    T = table({fidelity}, {comp_s}, {exp_s}, {err_s}, {alt_s}, {divergence}, {src}, {notes}, ...
        'VariableNames', {'Fidelity', 'Computed', 'Brandt', 'PctDiff', 'Alt', 'Divergence', 'Source', 'Notes'}, ...
        'RowNames', {name});
end

function T = srow(label)
%SROW  Section separator row.
    T = table({'---'}, {'---'}, {'---'}, {'---'}, {'---'}, {'---'}, {'---'}, {'---'}, ...
        'VariableNames', {'Fidelity', 'Computed', 'Brandt', 'PctDiff', 'Alt', 'Divergence', 'Source', 'Notes'}, ...
        'RowNames', {label});
end

function rows = table_to_rows(T)
%TABLE_TO_ROWS  Convert the comparison table to a struct array for jsonencode.
    n = height(T);
    for r = n:-1:1   % reverse iteration pre-allocates the struct array
        rows(r).parameter  = T.Properties.RowNames{r};
        rows(r).Fidelity   = T.Fidelity{r};
        rows(r).Computed   = T.Computed{r};
        rows(r).Brandt     = T.Brandt{r};
        rows(r).PctDiff    = T.PctDiff{r};
        rows(r).Alt        = T.Alt{r};
        rows(r).Divergence = T.Divergence{r};
        rows(r).Source     = T.Source{r};
        rows(r).Notes      = T.Notes{r};
    end
end

function write_markdown(T, out_path, W_TO, now_str, oew_brandt, oew_alt, gap_total)
%WRITE_MARKDOWN  Render the comparison table as a markdown file.
    fid = fopen(out_path, 'w');
    fprintf(fid, '# F-16A Block 10/15 — Weights vs Brandt Ground Truth\n\n');
    fprintf(fid, 'Generated %s. W_TO = %.0f lbf [Brandt Wt!B3 = Main!O15].\n\n', now_str, W_TO);
    fprintf(fid, ['Source: `VnV/BrandtF16A/GroundTruth/f16a_ground_truth.json` [`.weights`] ' ...
        '(Brandt-direct ground truth; every `Wt` cell in that block was re-read live over ' ...
        'Excel COM on 2026-07-25 — NOT `F16Baseline.m`, which is the older ground truth ' ...
        '`fidelity_comparison.m` uses).\n\n']);
    fprintf(fid, ['This is a **comparison report**, not a test — no pass/fail assertions, not part ' ...
        'of `run_all_tests`, and **nothing here may ever be used to backfill a unit test''s ' ...
        'expected value**. Where a quantity has multiple valid implementations, each option gets ' ...
        'its own row, and the *rejected* variants are reported too so the decisions stay ' ...
        'auditable.\n\n']);
    fprintf(fid, ['**Reading the `Divergence` column.** `BY DESIGN` marks a row where the framework ' ...
        'computes the *same kind* of quantity as Brandt but is *expected* to differ — a different ' ...
        'formula family, or a locked decision to use a different coefficient. **A large %%Diff on ' ...
        'a `BY DESIGN` row is the correct answer, not a defect.** `DEFINITIONAL` marks a row where ' ...
        'the two sides are *different kinds of quantity altogether* (uninstalled vs installed ' ...
        'engine weight, a minimum bound vs a central estimate, EXPOSED vs FULL tail area, a design ' ...
        'landing-weight rule vs a back-calculated subtotal) — there the %%Diff is not an error ' ...
        'measure at all, so do not chase it. Blank means it is a genuine agreement check, and a ' ...
        'large %%Diff there **is** worth chasing.\n\n']);
    fprintf(fid, ['**Reading the `Alt` column.** It carries the `corrections.xls Wt!*` figure ' ...
        '(Casey''s revised-weight workbook, per `F16Baseline.m:136`) where one exists. That is a ' ...
        '**second, different source** — *not* the original Brandt `Wt!*`. For OEW the two are ' ...
        '**%.2f** (`Brandt Wt!B12`, the Expected) and **%.2f** (`corrections.xls Wt!B12`), ' ...
        '%.2f %% apart. `TestWeights{L1,L2,L3}` used to assert the %.0f figure while *citing* ' ...
        '`Wt!B12` — review finding #14. That assertion was deleted from the unit tier in Phase 4 ' ...
        'and became the headline rows below.\n\n'], ...
        oew_brandt, oew_alt, 100*(oew_alt - oew_brandt)/oew_brandt, oew_alt);
    fprintf(fid, ['**Three standing caveats.** (1) Brandt''s structural line items are a psf × area ' ...
        'model with *his own* coefficients (`Wt!C7:H7` = wing 6.75 / fuselage 5.0 / pitch 6.0 / ' ...
        'VT 6.0 / nacelle 4.5 / strake 4.5 lbf/ft²); the framework''s L2 is psf × area with ' ...
        '**Raymer Table 15.2**''s coefficients (9 / 4.8 / 4 / 5.3), and L3 is the Raymer §15.3.1 ' ...
        'statistical build-up, which groups mass differently again. (2) Brandt''s tail line items ' ...
        'use the **FULL** planform areas (108 / 60 ft²); the framework uses the **EXPOSED** areas ' ...
        'per Raymer Table 15.2''s own definition. (3) **%.2f lbf** of Brandt''s weight statement ' ...
        '(%.2f %% of `Wt!B12`) has no framework analog at any fidelity level — nacelles, strakes, ' ...
        'a lumped "other structure" and armament support — which accounts for the bulk of every ' ...
        'negative OEW %%Diff below.\n\n'], gap_total, 100*gap_total/oew_brandt);
    fprintf(fid, '| Parameter | Fidelity | Computed | Brandt | %%Diff | Alt (corrections.xls) | Divergence | Source | Notes |\n');
    fprintf(fid, '|---|---|---|---|---|---|---|---|---|\n');
    n = height(T);
    for r = 1:n
        name = T.Properties.RowNames{r};
        if strcmp(T.Computed{r}, '---')
            fprintf(fid, '| **%s** | | | | | | | | |\n', strrep(name, '|', '\|'));
        else
            fprintf(fid, '| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n', ...
                strrep(name, '|', '\|'), T.Fidelity{r}, T.Computed{r}, T.Brandt{r}, T.PctDiff{r}, ...
                T.Alt{r}, T.Divergence{r}, ...
                strrep(T.Source{r}, '|', '\|'), strrep(T.Notes{r}, '|', '\|'));
        end
    end
    fclose(fid);
end
