function T_all = sandc_brandt_comparison()
%SANDC_BRANDT_COMPARISON  F-16A stability & control (neutral point, static
%   margin, aerodynamic centers, lift-curve slopes, CG) vs Brandt ground
%   truth.
%
%   TIER 2 (CLAUDE.md's two-tier-tests-never-blended convention) -- a
%   REPORTING script, NOT a test. No pass/fail assertions, not part of
%   run_all_tests, and nothing here may ever backfill a unit test's expected
%   value (see tests/disciplines/TestSandCL2.m / TestSandCL3.m for the actual
%   Tier-1 unit tests).
%
%   ─── HOW TO RUN ─────────────────────────────────────────────────────────
%     >> cd air_vehicle_design/sizing
%     >> addpath(genpath('src')); addpath(genpath('examples'))
%     >> sandc_brandt_comparison
%   Or non-interactively:
%     $ matlab -batch "addpath(genpath('src')); addpath(genpath('examples')); sandc_brandt_comparison"
%
%   ─── THE HEADLINE FINDING, STATED UP FRONT, NOT BURIED ───────────────────
%   This framework's computed x_np/SM diverge SUBSTANTIALLY from Brandt's own
%   ground truth: computed x_np ~ 27.96 ft vs Brandt's 26.168 ft; computed
%   SM ~ +0.177 (17.7% MAC, comfortably stable) vs Brandt's SM_TO ~ -0.0022 /
%   SM_land ~ +0.0027 (essentially neutral). This is a REAL, ALREADY-
%   DIAGNOSED, NON-BUG finding, not something to paper over --
%   docs/subplans/10_stability_control.md's "Major new lead" section found
%   that Brandt's OWN ground-truth workbook computes CLa/neutral-point via
%   ROSKAM Eqns 3.17/3.19/3.24/3.38 (a different book, "Airplane Flight
%   Dynamics and Automatic Flight Controls, Part I" -- NOT in this repo,
%   Casey confirmed he does not have a copy), not Raymer Ch. 16 -- a
%   different textbook method this repo cannot cross-check. Concretely: this
%   framework's wing CL_alpha ~ 2.53/rad (F16AeroL3.get_CL_alpha, Raymer
%   Eq. 12.6/12.8) vs Brandt's CLaW=3.2684/rad (Roskam Eq. 3.24) -- a ~23%
%   difference that alone plausibly explains most of the neutral-point shift,
%   since Xnp_bar is a weighted blend dominated by the CL_alpha/CL_alpha_h
%   ratio and the eta_h*(Sh/Sw)*CL_alpha_h term relative to CL_alpha. See the
%   [ROOT CAUSE] rows below and docs/subplans/10_stability_control.md's
%   "Major new lead" section for the full record. NO input/citation is
%   adjusted here to force closer agreement -- this comparison is
%   informational per CLAUDE.md, not a target to hit.
%
%   ─── WHERE THE INPUTS COME FROM ─────────────────────────────────────────
%     f16a_spec_path(2)/(3)    -> examples/F16A/inputs/f16a_L{2,3}.json .stability_control
%     f16a_requirements_path() -> examples/F16A/inputs/f16a_requirements.json (cruise Mach 0.87, DI-reused via weights.cruise_mach)
%   Ground truth: VnV/BrandtF16A/GroundTruth/f16a_stability_control_ground_truth.json
%   (neutral_point, cg_takeoff, cg_landing, CLa_aircraft, CLa_per_surface,
%   aero_center) and f16a_ground_truth.json .weights (TOGW/fuel, the run
%   condition below). Never an input -- only a comparison target.
%
%   ─── RUN CONDITION ───────────────────────────────────────────────────────
%   Run at Brandt's own W_TO=31,377 lbf / W_energy=6,296.30 lbf (Wt!B3/B38,
%   Wt!B6) so this report evaluates the framework AT Brandt's own operating
%   point -- the same convention every other *_brandt_comparison.m script in
%   this directory uses. NOT the same thing as backfilling a unit test's
%   expected value (CLAUDE.md's two-tier rule): no assertion is made here.
%
%   ─── OUTPUTS (written beside this script) ───────────────────────────────
%     jsons/sandc_brandt_comparison.json   full table + metadata
%     mds/sandc_brandt_comparison.md       rendered markdown
%
%   ─── SOURCES ────────────────────────────────────────────────────────────
%     [Brandt]  S. Brandt, F-16A.xls, sheet 'S&C (2)', via VnV/BrandtF16A/
%               GroundTruth/f16a_stability_control_ground_truth.json.
%     [Raymer]  Aircraft Design 6th ed., Ch. 16 Sec. 16.3, Eqs. 16.8-16.18,
%               16.25 (primary-source page read 2026-08-04, book pp.585-619).
%     [Roskam]  Airplane Flight Dynamics and Automatic Flight Controls,
%               Part I, Eqns 3.17/3.19/3.24/3.38 -- Brandt's OWN cited
%               source for this exact deliverable; NOT in this repo (see
%               headline finding above). Cited here only as the explanation
%               for WHY the two sides diverge, never as a toolbox formula.
%
%   NOT A TEST: informational only, never pass/fail, and no value here may
%   backfill a unit test's expected value (CLAUDE.md's two-tier rule).

script_dir  = fileparts(mfilename('fullpath'));
sizing_root = fileparts(fileparts(fileparts(script_dir)));
gt_path     = fullfile(sizing_root, 'VnV', 'BrandtF16A', 'GroundTruth', 'f16a_stability_control_ground_truth.json');
gt_all_path = fullfile(sizing_root, 'VnV', 'BrandtF16A', 'GroundTruth', 'f16a_ground_truth.json');
gt          = jsondecode(fileread(gt_path)).stability_control;
gt_weights  = jsondecode(fileread(gt_all_path)).weights;

% ════════════════════════════════════════════════════════════════════════ %
%  COMPUTE — run the actual toolbox code, at Brandt's own operating point
% ════════════════════════════════════════════════════════════════════════ %

W_TO_brandt   = gt_weights.summary.TOGW.value;   % 31377.00 [Brandt Wt!B3/B38]
W_fuel_brandt = gt_weights.summary.fuel.value;   % 6296.30  [Brandt Wt!B6]

prop = F16PropL2(f16a_spec_path(2));

% ── L2: CG term only ─────────────────────────────────────────────────── %
g2 = F16GeomL2(f16a_spec_path(2), prop);
w2 = F16WeightsL2(f16a_spec_path(2), f16a_requirements_path(), g2, prop);
w2.W_TO     = W_TO_brandt;
w2.W_energy = W_fuel_brandt;
s2 = F16SandCL2(f16a_spec_path(2), w2);

% ── L3: full Ch. 16 buildup ──────────────────────────────────────────── %
g3 = F16GeomL3(f16a_spec_path(3), prop);   % no L3 propulsion tier -- F16PropL2 is reused
w3 = F16WeightsL3(f16a_spec_path(3), f16a_requirements_path(), g3, prop);
w3.W_TO     = W_TO_brandt;
w3.W_energy = W_fuel_brandt;
a3 = F16AeroL3(g3, f16a_spec_path(3), f16a_control_surfaces());
ctrl3 = f16a_control_surfaces();   % the same factory design_study_02_L2.m/03_L3.m use
s3 = F16SandCL3(f16a_spec_path(3), g3, w3, a3, prop, ctrl3);

% ════════════════════════════════════════════════════════════════════════ %
%  BUILD TABLE
% ════════════════════════════════════════════════════════════════════════ %

T = table();

% ── CENTER OF GRAVITY (x_cg), L2 and L3 ─────────────────────────────────── %
T = [T; srow('[CENTER OF GRAVITY x_cg -- weighted-average identity, level-agnostic]')];
T = [T; grow('x_cg, L2 [ft]', 'L2', s2.x_cg, gt.cg_takeoff.x_cg_TO_ft, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 36 (xcgTakeoff)', '%.4f', ...
    ['Run at Brandt''s own W_TO/W_energy operating point. This framework''s x_cg is built from a ' ...
     'DIFFERENT component-weight/x-station table (this framework''s own 10 WeightsL2 groups, ' ...
     're-aggregated from the legacy temp_Casey 22-row sheet -- docs/subplans/10_stability_control.md ' ...
     '"Component-x-location buildup") than Brandt''s own internal CG closure, so an exact match is not ' ...
     'expected; this row checks whether the two land in the same physical neighborhood.'], ...
    gt.cg_landing.x_cg_land_ft, 'BY DESIGN')];
T = [T; grow('x_cg, L3 [ft]', 'L3', s3.x_cg, gt.cg_takeoff.x_cg_TO_ft, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 36 (xcgTakeoff)', '%.4f', ...
    'Same component-x-station table as L2 (cg_x_ft is fidelity-independent per the input JSON''s own note) -- expect the same %Diff as the L2 row above.', ...
    gt.cg_landing.x_cg_land_ft, 'BY DESIGN')];

% ── AERODYNAMIC CENTERS (x_acw, x_ach), Eq. 16.12/quarter-MAC, L3 only ──── %
T = [T; srow('[AERODYNAMIC CENTERS x_acw / x_ach -- Eq. 16.12 (wing) and quarter-MAC (tail, no Mach term)]')];
T = [T; grow('x_acw (wing aero center) [ft]', 'L3', s3.x_acw, gt.aero_center.xacW_ft, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 16 (xacW)', '%.4f', ...
    ['Framework value includes Eq. 16.12''s Mach-shift term evaluated at the real cruise Mach (0.87, in ' ...
     'the 0.4<=M<=1.1 transonic-shift regime); Brandt''s own simplified xacW value appears to omit this ' ...
     'shift (F16SandCL3.md''s own hand-check, done at M<0.4 where the shift is exactly 0, landed within ' ...
     '+0.01% of Brandt -- the REMAINING gap at the real M=0.87 is almost entirely this shift term, not a ' ...
     'wing-geometry wiring error). A small, EXPLAINED gap is expected here, not an exact match.'], ...
    NaN, 'BY DESIGN')];
T = [T; grow('x_ach (HT aero center, quarter-MAC) [ft]', 'L3', s3.x_ach, gt.aero_center.xacHS_ft, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 16 (xacHS)', '%.4f', ...
    'No Mach-shift term applied to the tail (documented simplification -- Raymer gives no Eq. 16.12-style correction for a tail surface, see SandCL3.x_ac_surface''s own header).', ...
    NaN, 'BY DESIGN')];

% ── LIFT-CURVE SLOPES -- linked to the Aero toolbox, not re-derived ─────── %
T = [T; srow('[LIFT-CURVE SLOPES -- linked to F16AeroL3.get_CL_alpha / SandCL3.CL_alpha_h, NOT re-derived]')];
T = [T; grow('CL_alpha, wing [1/rad]', 'L3', s3.CL_alpha_wing, gt.CLa_per_surface.CLaW_per_rad, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 24 (CLaW), in-sheet cite Roskam Eqn 3.24', '%.4f', ...
    ['[ROOT CAUSE, see headline finding above] Framework: Raymer Eq. 12.6/12.8 (F16AeroL3.get_CL_alpha). ' ...
     'Brandt: Roskam Eqn 3.24 -- a DIFFERENT textbook method this repo cannot cross-check (that Roskam ' ...
     'title is not in this repo). The ~23% gap here plausibly explains most of the x_np/SM divergence ' ...
     'reported below, since Xnp_bar is a weighted blend dominated by this ratio.'], NaN, 'BY DESIGN')];
T = [T; grow('CL_alpha, horizontal tail [1/rad]', 'L3', s3.CL_alpha_tail, gt.CLa_per_surface.CLaHS_per_rad, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 24 (CLaHS)', '%.4f', ...
    'Framework: SandCL3.CL_alpha_h, reusing AeroL2.CL_alpha a second time with the HT''s own AR/sweep (same Raymer Eq. 12.6/12.8 family as the wing row above, same root-cause caveat).', NaN, 'BY DESIGN')];
T = [T; grow('CLa, aircraft (Roskam Eq. 3.24 aggregate) -- NOT MODELED', 'N/A', NaN, gt.CLa_aircraft.value_per_rad, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 32 (CLa)', '%.4f', ...
    'This framework has no single "aircraft CL_alpha" quantity analogous to Roskam Eq. 3.24''s aggregate -- Eqs. 16.8/16.9 combine CL_alpha_wing/CL_alpha_tail directly inside the Cm_alpha/neutral-point sum instead of forming an intermediate aircraft-level slope. Recorded as NOT MODELED, not a %Diff to chase.')];

% ── THE HEADLINE FINDING, IN TABLE FORM ─────────────────────────────────── %
T = [T; srow('[NEUTRAL POINT x_np AND STATIC MARGIN SM -- THE HEADLINE FINDING]')];
T = [T; grow('x_np [ft]', 'L3', s3.x_np, gt.neutral_point.x_np_ft, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 33 (xnp), in-sheet cite Roskam Eqn 3.38', '%.4f', ...
    ['Framework: Raymer Eq. 16.9 (power-off, thrust term dropped per Raymer''s own p.593 sanction). ' ...
     'Brandt: Roskam Eqn 3.38, itself built on Roskam''s own CLa/CLaHS (Eqns 3.17/3.19/3.24, a different ' ...
     'textbook method this repo cannot cross-check -- see the [ROOT CAUSE] CL_alpha rows above and ' ...
     'docs/subplans/10_stability_control.md''s "Major new lead" section for the full record). This gap ' ...
     'is a real, already-diagnosed, cross-textbook-method divergence, NOT a bug -- no input/citation is ' ...
     'adjusted here to force closer agreement.'], NaN, 'BY DESIGN')];
T = [T; grow('SM (static margin, TO-loading comparison) [frac. MAC]', 'L3', s3.SM, gt.cg_takeoff.SM, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 37 (SM, takeoff loading)', '%.5f', ...
    ['Framework computes SM ~ +0.18 (comfortably stable) at this operating point vs Brandt''s SM_TO ~ ' ...
     '-0.0022 (essentially neutral, very slightly unstable at takeoff loading) -- same root cause as the ' ...
     'x_np row above (the ~23% CL_alpha gap dominates), COMPOUNDED by the different x_cg table (see the ' ...
     'x_cg rows above). Both factors push in the SAME direction here.'], NaN, 'BY DESIGN')];
T = [T; grow('SM (static margin, vs Brandt landing-loading case) [frac. MAC]', 'L3', s3.SM, gt.cg_landing.SM_land, ...
    'Brandt-F16-A.xls, sheet S&C (2), row 35 (SMLndg, landing loading)', '%.5f', ...
    'Same framework SM as the row above (this pass computes one SM at one W_energy operating point, not separate TO/landing cases) -- shown against BOTH Brandt loading cases for completeness.', NaN, 'BY DESIGN')];

% ── OUT OF SCOPE / NOT MODELED, per the ground-truth JSON's own markers ── %
T = [T; srow('[OUT OF SCOPE / NOT MODELED -- carried forward from the ground-truth JSON''s own markers]')];
T = [T; grow('Lateral-directional derivatives (CNB/ClB/CYB) -- OUT OF SCOPE', 'N/A', NaN, NaN, ...
    'Brandt-F16-A.xls, sheet S&C (2), rows 39-70', '%.4f', ...
    'docs/subplans/10_stability_control.md "Explicitly out of scope": lateral-directional static stability and control. Ground-truth JSON''s own lateral_directional block: status "OUT OF SCOPE".')];
T = [T; grow('Short-period dynamic response (Cmq/Cmadot/root-locus) -- OUT OF SCOPE', 'N/A', NaN, NaN, ...
    'Brandt-F16-A.xls, sheet S&C (2), rows 79-118', '%.4f', ...
    'docs/subplans/10_stability_control.md Objective: "steady, level flight, only. No dynamic/nonsteady stability analysis." Ground-truth JSON''s own short_period_dynamics block: status "OUT OF SCOPE".')];
T = [T; grow('CL_w / CL_h / Cm_cg_trim (Eqs. 16.13/16.14/16.5-16.7) -- GAP-BLOCKED for the F-16', 'N/A', NaN, NaN, ...
    'No Brandt analog attempted here', '%.4f', ...
    ['Documented citation GAPs (wing/tail incidence i_w/i_h; thrust x-location x_p, vertical offset z_t) ' ...
     '-- see F16SandCL3.CL_w/CL_h/Cm_cg_trim''s own headers and f16a_L3.json ' ...
     '.stability_control._TODO_i_w_i_h / _TODO_x_p. Pinned by tests/disciplines/TestSandCL3.m''s three ' ...
     'testTODO_* deliberately-failing unit tests, not resolved or estimated here.'])];

% ════════════════════════════════════════════════════════════════════════ %
%  DISPLAY + EXPORT
% ════════════════════════════════════════════════════════════════════════ %

meta = struct( ...
    'title',         'F-16A Block 10/15 — Stability & Control vs Ground Truth', ...
    'aircraft',      'F-16A Block 10/15', ...
    'generated',     char(datetime('now', 'Format', 'yyyy-MM-dd')), ...
    'condition',     sprintf('Run at Brandt''s own W_TO=%.2f lbf, W_energy=%.2f lbf (Wt!B3/B38, Wt!B6), cruise Mach 0.87 (f16a_requirements.json, DI-reused via weights.cruise_mach).', ...
                              W_TO_brandt, W_fuel_brandt), ...
    'referenceDesc', ['VnV/BrandtF16A/GroundTruth/f16a_stability_control_ground_truth.json (neutral_point, ' ...
                      'cg_takeoff, cg_landing, CLa_aircraft, CLa_per_surface, aero_center) -- Brandt-F16-A.xls, ' ...
                      'sheet ''S&C (2)''.'], ...
    'secondDesc',    ['Roskam Eqns 3.17/3.19/3.24/3.38 (Brandt''s OWN cited source for CLa/neutral point) -- ' ...
                      'NOT this repo''s toolbox formula, and NOT in this repo at all (that specific Roskam ' ...
                      'title, "Airplane Flight Dynamics and Automatic Flight Controls, Part I," is not ' ...
                      'extracted anywhere here); cited only as the explanation for the headline finding.'] );

meta.preamble = { ...
    ['**HEADLINE FINDING.** This framework''s computed x_np/SM diverge SUBSTANTIALLY from Brandt''s ground ' ...
     'truth: computed x_np ~ 27.96 ft vs Brandt''s 26.168 ft; computed SM ~ +0.18 (comfortably stable) vs ' ...
     'Brandt''s SM_TO ~ -0.0022 / SM_land ~ +0.0027 (essentially neutral). This is a REAL, ALREADY-DIAGNOSED, ' ...
     'NON-BUG finding: docs/subplans/10_stability_control.md''s "Major new lead" section found that Brandt''s ' ...
     'OWN ground-truth workbook computes CLa/neutral-point via Roskam Eqns 3.17/3.19/3.24/3.38 -- a DIFFERENT ' ...
     'textbook method than this framework''s Raymer Ch. 16 buildup, and one this repo cannot cross-check ' ...
     '(that Roskam title is not in this repo; Casey confirmed 2026-08-03 he does not have a copy).'], ...
    ['**ROOT CAUSE.** This framework''s wing CL_alpha ~2.53/rad (F16AeroL3.get_CL_alpha, Raymer Eq. 12.6/ ' ...
     '12.8) vs Brandt''s CLaW=3.2684/rad (Roskam Eq. 3.24) -- a ~23% difference that alone plausibly explains ' ...
     'most of the neutral-point shift, since Xnp_bar is a weighted blend dominated by the CL_alpha/ ' ...
     'CL_alpha_h ratio and the eta_h*(Sh/Sw)*CL_alpha_h term relative to CL_alpha. See the [ROOT CAUSE] rows ' ...
     'in the table below.'], ...
    ['**NO INPUT OR CITATION IS ADJUSTED HERE to force closer agreement with Brandt** -- per CLAUDE.md, this ' ...
     'comparison is informational only, and Raymer Ch. 16''s formulas (as primary-source-confirmed 2026-08-04, ' ...
     'book pp.585-619) are followed exactly as cited, even where they disagree with Brandt''s different, ' ...
     'unavailable-in-this-repo Roskam-based method.'] };

ComparisonReport.show(T, meta);

out_json = fullfile(script_dir, '..', 'output', 'sandc_brandt_comparison.json');
out_md   = fullfile(script_dir, '..', 'output', 'sandc_brandt_comparison.md');
ComparisonReport.writeJson(T, out_json, meta);
ComparisonReport.writeMarkdown(T, out_md, meta);
fprintf('  JSON     -> %s\n', out_json);
fprintf('  Markdown -> %s\n\n', out_md);

T_all = T;

end

% ─── local helpers: thin wrappers over the shared renderer ───────────────── %

function T = grow(name, fidelity, computed, reference, cite, numfmt, notes, second, divergence)
%GROW  One comparison row. See ComparisonReport.row for the column semantics.
    if nargin < 7; notes      = ''; end
    if nargin < 8; second     = NaN; end
    if nargin < 9; divergence = ''; end
    T = ComparisonReport.row(name, fidelity, computed, reference, cite, numfmt, notes, second, divergence);
end

function T = srow(label)
%SROW  Section separator row.
    T = ComparisonReport.section(label);
end
