function T_all = subsystems_brandt_comparison()
%SUBSYSTEMS_BRANDT_COMPARISON  F-16A subsystems (fuel/avionics volume,
%   landing-gear tire size) vs Brandt ground truth.
%
%   TIER 2 (CLAUDE.md's two-tier-tests-never-blended convention) -- a
%   REPORTING script, NOT a test. No pass/fail assertions, not part of
%   run_all_tests, and nothing here may ever backfill a unit test's
%   expected value (see tests/disciplines/TestSubsystemsL1/L2/L3.m and
%   TestF16LandingGearL2/L3.m for the actual Tier-1 unit tests).
%
%   ─── HOW TO RUN ─────────────────────────────────────────────────────────
%     >> cd air_vehicle_design/sizing
%     >> addpath(genpath('src')); addpath(genpath('examples'))
%     >> subsystems_brandt_comparison
%   Or non-interactively:
%     $ matlab -batch "addpath(genpath('src')); addpath(genpath('examples')); subsystems_brandt_comparison"
%
%   ─── WHAT THIS REPORT COVERS, AND WHY MOST OF IT IS "NOT MODELED" ───────
%   Per the original step-9 subsystems design's "Ground Truth" section,
%   confirmed 2026-07-31: VnV/BrandtF16A/GroundTruth/*.json has NO
%   fuel-volume or avionics-volume ground truth anywhere --
%   f16a_ground_truth.json's
%   .weights entries for fuel (6296.30 lb, Wt!B6) and avionics (2541.54 lb,
%   Wt!B30 = 0.081*W_TO) are Brandt WEIGHTS, not volumes, and converting them
%   to a volume would require the same uncited fuel density the weights side
%   already flags as an open gap (f16a_L3.json .weights.systems.V_t). This
%   report therefore carries HONEST "NOT MODELED" gap rows for both --
%   reporting what the framework itself computes (an internal self-
%   consistency figure) rather than fabricating a Brandt comparison that
%   does not exist.
%
%   Landing-gear tire/strut size DOES have an independent Brandt data point
%   (f16a_subsystems_ground_truth.json's landing_gear_tire_diameter block,
%   d_nose_ft=1.5 / d_main_ft=2.0), but it carries TWO caveats that this
%   report carries forward rather than hiding behind a clean-looking %Diff:
%     (1) UNDOCUMENTED PROVENANCE -- the block's only citation anywhere in
%         VnV/BrandtF16A is its own "_source": "Gear tab -- landing gear
%         geometry", no cell letter/number; readme_geom.md's Input Schema
%         and GroundTruth/cell-map.md both omit it entirely.
%     (2) LOAD-SPLIT CONTRADICTION -- the same gear block's x/y/h fields
%         feed BrandtBalanceStabControl.m's own gear-load-split calculation,
%         which returns 26.7% main / 73.3% nose -- a near-complete REVERSAL
%         of both Raymer's stated 90%/10% typical fighter split (Ch.11
%         p.344, which this framework uses by default) and Nicolai &
%         Carichner's own repo-documented "nose gear ~20% of TOGW" rule of
%         thumb. See VnV/BrandtF16A/todo.md, 2026-07-31 entry, and
%         f16a_subsystems_ground_truth.json's own caveat fields (carried
%         forward verbatim below, not re-derived or "corrected").
%
%   ─── OUTPUTS (written beside this script) ───────────────────────────────
%     jsons/subsystems_brandt_comparison.json   full table + metadata
%     mds/subsystems_brandt_comparison.md       rendered markdown
%
%   ─── SOURCES ────────────────────────────────────────────────────────────
%     [Brandt]  S. Brandt, F-16A.xls, via VnV/BrandtF16A/GroundTruth/
%               f16a_subsystems_ground_truth.json and f16a_ground_truth.json
%               (.weights.summary.fuel / .weights.engine_and_systems.avionics).
%     [Raymer]  Aircraft Design 6th ed., Ch.7 Eq.7.14 (fuselage volume),
%               Table 11.6 p.375 (avionics fraction/density), Ch.11 p.344 +
%               Table 11.1 (gear load split + statistical tire sizing).
%     [Roskam]  Airplane Design Part II, Ch.6, Eq.6.2/6.3 (wing fuel volume).
%     [Nicolai] Nicolai & Carichner, Ch.8 p.210 (fuel density / packaging
%               factors; avionics density Sec.8.1.11), p.202 (nose-gear
%               rule of thumb).
%
%   NOT A TEST: informational only, never pass/fail, and no value here may
%   backfill a unit test's expected value (CLAUDE.md's two-tier rule).

script_dir  = fileparts(mfilename('fullpath'));
sizing_root = fileparts(fileparts(fileparts(script_dir)));
gt_path     = fullfile(sizing_root, 'VnV', 'BrandtF16A', 'GroundTruth', 'f16a_subsystems_ground_truth.json');
gt_all_path = fullfile(sizing_root, 'VnV', 'BrandtF16A', 'GroundTruth', 'f16a_ground_truth.json');
gt          = jsondecode(fileread(gt_path)).subsystems;
gt_weights  = jsondecode(fileread(gt_all_path)).weights;

% ════════════════════════════════════════════════════════════════════════ %
%  COMPUTE — run the actual toolbox code
% ════════════════════════════════════════════════════════════════════════ %
%
%  Run condition: Brandt's own TOGW (31,377 lb) and internal-fuel weight
%  (6,296.30 lb, Wt!B6) are used here as the sizing-loop STATE / mission-
%  analysis inputs so this report evaluates the framework AT Brandt's own
%  operating point -- exactly how every other *_brandt_comparison.m script
%  in this directory runs the framework at Brandt's spec inputs. This is
%  NOT the same thing as backfilling a unit test's expected value from
%  Brandt output (CLAUDE.md's two-tier rule): no assertion is made here.

W_TO_brandt  = gt_weights.summary.TOGW.value;   % 31377.00  [Brandt Wt!B3/B38]
W_fuel_brandt = gt_weights.summary.fuel.value;   % 6296.30   [Brandt Wt!B6]
OEW_brandt    = gt_weights.summary.OEW.value;    % 19980.70  [Brandt Wt!B12]
W_avionics_brandt = gt_weights.engine_and_systems.avionics.value;   % 2541.54 [Brandt Wt!B30]

% ── L1: tabulation only ──────────────────────────────────────────────── %
s1 = F16SubsystemsL1(f16a_spec_path(1));
r1_internal_volume = s1.internal_volume(OEW_brandt);
r1_avionics_volume = s1.avionics_volume(OEW_brandt);
r1_avionics_weight  = s1.avionics_weight(OEW_brandt);
r1_fuel_check       = s1.fuel_volume_check(W_fuel_brandt);

% ── L2: geometry-derived ─────────────────────────────────────────────── %
prop2 = F16PropL2(f16a_spec_path(2));
g2    = F16GeomL2(f16a_spec_path(2), prop2);
w2    = F16WeightsL2(f16a_spec_path(2), f16a_requirements_path(), g2, prop2);
w2.W_TO     = W_TO_brandt;
w2.W_energy = W_fuel_brandt;
s2  = F16SubsystemsL2(f16a_spec_path(2), g2, w2);
lg2 = F16LandingGearL2(f16a_spec_path(2), w2);
r2_fuel_check = s2.fuel_volume_check();

% ── L3: refined geometry-derived ─────────────────────────────────────── %
g3 = F16GeomL3(f16a_spec_path(3), prop2);   % no L3 propulsion tier -- F16PropL2 is reused
w3 = F16WeightsL3(f16a_spec_path(3), f16a_requirements_path(), g3, prop2);
w3.W_TO     = W_TO_brandt;
w3.W_energy = W_fuel_brandt;
s3  = F16SubsystemsL3(f16a_spec_path(3), g3, w3);
lg3 = F16LandingGearL3(f16a_spec_path(3), w3);
r3_fuel_check = s3.fuel_volume_check();

% ════════════════════════════════════════════════════════════════════════ %
%  BUILD TABLE
% ════════════════════════════════════════════════════════════════════════ %

T = table();

% ── FUEL VOLUME -- NOT MODELED IN BRANDT GROUND TRUTH ───────────────────── %
T = [T; srow('[FUEL VOLUME -- NOT MODELED IN BRANDT GROUND TRUTH]')];
T = [T; grow('Fuselage usable fuel volume, L2 [ft^3]', 'L2', s2.fuselage_usable_fuel_volume, NaN, ...
    gt.fuel_volume.status, '%.4f', gt.fuel_volume.x_note)];  % jsondecode renames leading-underscore JSON keys "_note" -> "x_note"
T = [T; grow('Wing fuel volume, L2 [ft^3]', 'L2', s2.wing_fuel_volume, NaN, ...
    gt.fuel_volume.status, '%.4f', 'Roskam Eq. 6.2/6.3 -- no Brandt volume analog either.')];
T = [T; grow('Total available fuel volume (fuselage+wing), L2 [ft^3]', 'L2', ...
    r2_fuel_check.available_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', ...
    'Sum of BOTH fuselage AND wing terms (never just one -- Legacy Bug guard).')];
T = [T; grow('Required fuel volume from W_energy=6296.30 lb @ JP-8 density, L2 [ft^3]', 'L2', ...
    r2_fuel_check.required_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', ...
    ['Brandt Wt!B6 fuel WEIGHT (6296.30 lb) run through the framework''s own JP-8 density ' ...
     '(50 lb/ft^3, Nicolai Table 8.6) -- an internal self-consistency figure, NOT a Brandt ' ...
     'volume comparison (no such ground truth exists; do not repurpose the weight as one).'])];
T = [T; grow('Fuel volume margin (available - required), L2 [ft^3]', 'L2', ...
    r2_fuel_check.available_vol_ft3 - r2_fuel_check.required_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', ...
    sprintf('sufficient = %s at Brandt''s own W_TO/W_energy operating point.', mat2str(r2_fuel_check.sufficient)))];

T = [T; grow('Total available fuel volume (fuselage+wing), L3 [ft^3]', 'L3', ...
    r3_fuel_check.available_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', ...
    'L3 refines the fuselage term with frame-integrated station areas instead of L2''s envelope ellipse.')];
T = [T; grow('Required fuel volume from W_energy=6296.30 lb @ JP-8 density, L3 [ft^3]', 'L3', ...
    r3_fuel_check.required_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', 'Same density path as L2 -- level-agnostic.')];
T = [T; grow('Fuel volume margin (available - required), L3 [ft^3]', 'L3', ...
    r3_fuel_check.available_vol_ft3 - r3_fuel_check.required_vol_ft3, NaN, gt.fuel_volume.status, '%.4f', ...
    sprintf('sufficient = %s at Brandt''s own W_TO/W_energy operating point.', mat2str(r3_fuel_check.sufficient)))];

T = [T; grow('Internal volume (avionics only), L1 [ft^3]', 'L1', r1_internal_volume, NaN, ...
    gt.fuel_volume.status, '%.4f', ['L1 has no fuel-bay geometry -- internal_volume() is avionics ' ...
     'volume only. required_vol_ft3 for W_fuel=6296.30 lb: see row below; available is honestly 0.'])];
T = [T; grow('L1 fuel_volume_check: required volume [ft^3]', 'L1', r1_fuel_check.required_vol_ft3, NaN, ...
    gt.fuel_volume.status, '%.4f', 'available_vol_ft3 is honestly reported as 0 at L1 (no fuel-bay geometry exists yet).')];

% ── AVIONICS VOLUME -- NOT MODELED IN BRANDT GROUND TRUTH ───────────────── %
T = [T; srow('[AVIONICS VOLUME -- NOT MODELED IN BRANDT GROUND TRUTH]')];
T = [T; grow('Avionics volume, L1 [ft^3]', 'L1', r1_avionics_volume, NaN, gt.avionics_volume.status, '%.4f', ...
    'Raymer Table 11.6 fraction (0.055) x Raymer''s own following-paragraph density average (37.5 lb/ft^3).')];
T = [T; grow('Avionics volume, L2 [ft^3]', 'L2', s2.avionics_volume, NaN, gt.avionics_volume.status, '%.4f', ...
    'Same 0.055 fraction, but Nicolai''s flat 45 lb/ft^3 density (Sec.8.1.11) -- the L2/L3 fidelity split.')];
T = [T; grow('Avionics volume, L3 [ft^3]', 'L3', s3.avionics_volume, NaN, gt.avionics_volume.status, '%.4f', ...
    'Identical equation to L2 -- avionics volume does not depend on fuselage-envelope fidelity.')];
T = [T; grow('Avionics WEIGHT cross-check (bonus, different basis), L1 [lbf]', 'L1', r1_avionics_weight, ...
    W_avionics_brandt, 'Brandt Wt!B30 = 0.081*W_TO', '%.2f', ...
    ['DEFINITIONAL, do not conflate: framework uses Raymer Table 11.6''s 0.055 x W_EMPTY (an ' ...
     'aircraft-empty-weight fraction); Brandt uses its own uncited 0.081 x W_TO (a takeoff-weight ' ...
     'fraction) -- two different weight BASES from two different sources, not two estimates of the ' ...
     'same formula. A large %Diff here is not a framework error to chase.'], NaN, 'DEFINITIONAL')];

% ── LANDING GEAR TIRE SIZE (Brandt data point exists, TWO caveats apply) ── %
T = [T; srow('[LANDING GEAR TIRE/STRUT SIZE -- BRANDT DATA POINT EXISTS, TWO CAVEATS APPLY]')];
T = [T; grow('Main tire diameter, L2 [in]', 'L2', lg2.tire_diameter_main, gt.landing_gear_tire_diameter.d_main_ft*12, ...
    'Brandt "Gear tab" (f16a_geometry.json gear block) -- UNDOCUMENTED cell reference', '%.4f', ...
    ['CAVEAT 1 (undocumented provenance): this Brandt figure''s only citation anywhere in VnV/BrandtF16A ' ...
     'is the JSON''s own "_source": "Gear tab -- landing gear geometry", no cell letter/number; ' ...
     'readme_geom.md''s Input Schema and cell-map.md both omit it entirely. CAVEAT 2 (load-split ' ...
     'contradiction): the SAME Brandt gear block implies a 26.7% main / 73.3% nose load split (see the ' ...
     'Gear Load Split section below) -- a near-reversal of the Raymer 90/10 split this tire-diameter ' ...
     'formula actually uses. Report this %Diff, but do not treat it as a clean validation.'], NaN, 'BY DESIGN')];
T = [T; grow('Nose tire diameter, L2 [in]', 'L2', lg2.tire_diameter_nose, gt.landing_gear_tire_diameter.d_nose_ft*12, ...
    'Brandt "Gear tab" -- same two caveats as the main-tire row above', '%.4f', ...
    'Framework: 0.80 x main-tire diameter (Raymer''s stated 60-100% range, midpoint). Same caveats apply.', ...
    NaN, 'BY DESIGN')];
T = [T; grow('Main tire diameter, L3 [in]', 'L3', lg3.tire_diameter_main, gt.landing_gear_tire_diameter.d_main_ft*12, ...
    'Brandt "Gear tab" -- same two caveats', '%.4f', ...
    'Identical to L2 -- tire sizing depends only on W_TO and the gear-load split, not geometry fidelity.', ...
    NaN, 'BY DESIGN')];
T = [T; grow('Nose tire diameter, L3 [in]', 'L3', lg3.tire_diameter_nose, gt.landing_gear_tire_diameter.d_nose_ft*12, ...
    'Brandt "Gear tab" -- same two caveats', '%.4f', 'Identical to L2.', NaN, 'BY DESIGN')];
T = [T; grow('Main tire width, L2 [in] -- NOT MODELED IN BRANDT', 'L2', lg2.tire_width_main, NaN, ...
    'N/A -- Brandt gear block has no tire-width field', '%.4f', ...
    'Raymer Table 11.1 gives a width formula too (A''=0.0980, B''=0.467, Jet fighter/trainer row); Brandt''s gear block carries diameters only.')];

% ── GEAR LOAD SPLIT -- the load-split contradiction, in full ─────────────── %
T = [T; srow('[GEAR LOAD SPLIT -- THE UNDERLYING CONTRADICTION BEHIND CAVEAT 2 ABOVE]')];
T = [T; grow('Main gear load, % of W_TO (framework default)', 'L2/L3', lg2.main_pct, ...
    gt.gear_load_split_comparison.brandt_derived.main_pct, ...
    'Brandt-derived, BrandtBalanceStabControl.m gear_main_pct off the same uncross-checked gear block', '%.1f', ...
    ['Framework uses Raymer''s stated typical fighter split (Ch.11 p.344 prose) as its DECIDED default, ' ...
     'deliberately NOT the Brandt-derived figure -- VnV/BrandtF16A/todo.md 2026-07-31 entry. The huge ' ...
     '%Diff here is the expected signature of that locked decision, not a framework defect.'], NaN, 'BY DESIGN')];
T = [T; grow('Nose gear load, % of W_TO (framework default)', 'L2/L3', lg2.nose_pct, ...
    gt.gear_load_split_comparison.brandt_derived.nose_pct, ...
    'Brandt-derived, same source as above', '%.1f', ...
    'Mirror of the main-gear row above -- main_pct+nose_pct sum to 100% on both sides by construction.', ...
    NaN, 'BY DESIGN')];
T = [T; grow('Nose gear load, % of W_TO, vs Nicolai''s OWN rule of thumb', 'L2/L3', lg2.nose_pct, ...
    gt.gear_load_split_comparison.nicolai_rule_of_thumb.nose_pct, ...
    '[Nicolai & Carichner, p.202]: "Nose gear rule of thumb: 20% of TOGW on the nose wheel"', '%.1f', ...
    ['A THIRD, independent data point: Nicolai''s own repo-documented rule of thumb (20% nose) is ' ...
     'exactly DOUBLE the framework''s Raymer-derived default (10%), and both published-textbook figures ' ...
     'disagree with the Brandt-derived 73.3% by an even larger margin. Worth a sanity check, though ' ...
     'neither Raymer nor Nicolai claims a single point value for this design-dependent split.'], NaN, 'BY DESIGN')];

% ── GAPS: battery volume, gear bay volume (documented citation gaps) ────── %
T = [T; srow('[DOCUMENTED CITATION GAPS -- NOT A BRANDT COMPARISON AT ALL]')];
T = [T; grow('Battery-electric volume path -- GAP, no citation', 'N/A', NaN, NaN, ...
    'No Brandt analog (F-16A is not electric)', '%.4f', ...
    ['No citable BATTERY VOLUMETRIC energy ' ...
     'density exists anywhere in this repo (only gravimetric, Nicolai Table 14.2 p.363). ' ...
     'SubsystemsL2/L3.battery_volume documented to error rather than fabricate a coefficient -- pinned ' ...
     'by tests/disciplines/TestSubsystemsL2.testTODO_BatteryVolumetricEnergyDensityNotInRepo.'])];
T = [T; grow('Gear bay volume (tire+strut stowage) -- GAP, no citation', 'N/A', NaN, NaN, ...
    'No Brandt bay-volume figure exists', '%.4f', ...
    ['No textbook bay-volume packaging ' ...
     'formula was found anywhere in this repo (Raymer Ch.11 covers tire/strut/shock-absorber SIZE only, ' ...
     'fully modeled above). F16LandingGearL2/L3.bay_volume documented to error -- pinned by ' ...
     'tests/disciplines/TestF16LandingGearL2.testTODO_GearBayVolumePackagingNotInRepo.'])];

% ════════════════════════════════════════════════════════════════════════ %
%  DISPLAY + EXPORT
% ════════════════════════════════════════════════════════════════════════ %

meta = struct( ...
    'title',         'F-16A Block 10/15 — Subsystems (Fuel/Avionics Volume, Landing Gear) vs Ground Truth', ...
    'aircraft',      'F-16A Block 10/15', ...
    'generated',     char(datetime('now', 'Format', 'yyyy-MM-dd')), ...
    'condition',     sprintf('Run at Brandt''s own W_TO=%.2f lbf, W_energy=%.2f lbf (Wt!B3/B38, Wt!B6).', ...
                              W_TO_brandt, W_fuel_brandt), ...
    'referenceDesc', ['VnV/BrandtF16A/GroundTruth/f16a_subsystems_ground_truth.json (fuel/avionics ' ...
                      'volume, landing-gear tire diameter) and f16a_ground_truth.json .weights (fuel/' ...
                      'avionics WEIGHT, cross-check rows only).'], ...
    'secondDesc',    ['Nicolai & Carichner''s independently-published "nose gear ~20% of TOGW" rule of ' ...
                      'thumb (p.202) -- a THIRD data point for the gear-load-split question, alongside ' ...
                      'Raymer''s 90/10 (used) and Brandt''s derived 26.7/73.3 (not used).'] );

meta.preamble = { ...
    ['**Most rows in this report are honestly "NOT MODELED" against Brandt**, not because the framework ' ...
     'fails to compute fuel/avionics volume (it does, at L2/L3), but because Brandt''s own workbook never ' ...
     'ground-truths a VOLUME for either quantity -- only WEIGHTS exist there, and this report does not ' ...
     'convert one to the other (that would require the same uncited fuel density the weights side already ' ...
     'flags as an open gap). See the original step-9 subsystems design''s "Ground Truth" section.'], ...
    ['**Landing-gear tire diameter is the one quantity with a real Brandt data point**, but it carries TWO ' ...
     'caveats this report deliberately does not hide: (1) the Brandt gear block''s only citation is an ' ...
     'undocumented "Gear tab" reference with no cell letter, omitted from readme_geom.md and cell-map.md; ' ...
     '(2) the SAME gear block implies a 26.7%/73.3% main/nose load split that nearly reverses both Raymer''s ' ...
     'typical-fighter 90/10 (used here by design) and Nicolai''s own 20%-nose rule of thumb. VnV/BrandtF16A/' ...
     'todo.md, 2026-07-31 entry, has the full record -- not resolved here, not resolved by this report.'], ...
    ['**Two equation items ship as documented citation gaps, not comparison rows**: battery-electric ' ...
     'volumetric energy density (item 7) and landing-gear bay-volume packaging (item 11). Both are pinned ' ...
     'by deliberately-labeled Tier-1 unit tests (testTODO_*), not resolved or estimated here.'] };

ComparisonReport.show(T, meta);

out_json = fullfile(script_dir, '..', 'output', 'subsystems_brandt_comparison.json');
out_md   = fullfile(script_dir, '..', 'output', 'subsystems_brandt_comparison.md');
ComparisonReport.writeJson(T, out_json, meta);
ComparisonReport.writeMarkdown(T, out_md, meta);
fprintf('  JSON     -> %s\n', out_json);
fprintf('  Markdown -> %s\n\n', out_md);

T_all = T;

end

% ─── local helpers: thin wrappers over the shared renderer ───────────────── %

function T = grow(name, fidelity, computed, reference, cite, numfmt, notes, second, divergence)
%GROW  One comparison row. See ComparisonReport.row for the column semantics.
    if nargin < 7; notes      = ''; end
    if nargin < 8; second     = NaN; end
    if nargin < 9; divergence = ''; end
    T = ComparisonReport.row(name, fidelity, computed, reference, cite, numfmt, notes, second, divergence);
end

function T = srow(label)
%SROW  Section separator row.
    T = ComparisonReport.section(label);
end
