function results = run_grader_tests(only)
%RUN_GRADER_TESTS  Run every IHW3 MATLAB Grader test against the files on the path.
%
%   results = run_grader_tests           every problem; errors if any test fails
%   results = run_grader_tests("P06")    one problem only; never errors
%
%   GENERATED by build_tests.py from the same source as IHW3_GRADER_SETUP.md.
%   Every test body below is printed verbatim on its problem card, so a test
%   that passes here passes in MATLAB Grader. Do not edit by hand.

    if nargin < 1, only = ""; end
    only = string(only);

    T = {
        'P01', 1, 'The constructor reads the regression', 2, @t_P01_T1
        'P01', 2, 'Engine size at P_SL = 600 hp', 2, @t_P01_T2
        'P01', 3, 'The engine follows P_SL', 1, @t_P01_T3
        'P01', 4, 'The range guard', 1, @t_P01_T4
        'P02', 1, 'The constructor reads the sub-blocks', 2, @t_P02_T1
        'P02', 2, 'The exposed wing', 3, @t_P02_T2
        'P02', 3, 'Tail sizing', 3, @t_P02_T3
        'P02', 4, 'Wetted areas', 3, @t_P02_T4
        'P02', 5, 'Everything follows S_ref and P_SL, except the fuselage', 2, @t_P02_T5
        'P02', 6, 'Wing fuel volume', 1, @t_P02_T6
        'P03', 1, 'Injection and the constructor', 2, @t_P03_T1
        'P03', 2, 'C_D0 and the polar at S_ref = 130, P_SL = 600', 3, @t_P03_T2
        'P03', 3, 'C_D0 follows the wing and the engine', 2, @t_P03_T3
        'P04', 1, 'Empty weight II, all seven rows', 4, @t_P04_T1
        'P04', 2, 'Evaluated at the PASSED weight', 2, @t_P04_T2
        'P04', 3, 'The build-up follows the geometry', 2, @t_P04_T3
        'P04', 4, 'Empty weight III', 3, @t_P04_T4
        'P04', 5, 'An unknown method stops the analysis', 1, @t_P04_T5
        'P05', 1, 'The power-index method is unchanged', 2, @t_P05_T1
        'P05', 2, 'The drag-based power balance', 3, @t_P05_T2
        'P05', 3, 'The limit follows the drag polar', 2, @t_P05_T3
        'P06', 1, 'The cruise weight fraction', 3, @t_P06_T1
        'P06', 2, 'Flown at the real lift coefficient', 2, @t_P06_T2
        'P06', 3, 'Flown with the current wing', 2, @t_P06_T3
        'P06', 4, 'The sub-segment count', 2, @t_P06_T4
        'P07', 1, 'The loiter weight fraction', 3, @t_P07_T1
        'P07', 2, 'Flown with the current wing, not the IHW1 rule', 2, @t_P07_T2
        'P08', 1, 'The first climb, sea level to 8000 ft', 3, @t_P08_T1
        'P08', 2, 'The second climb starts where the previous segment ended', 2, @t_P08_T2
        'P08', 3, 'The climb follows the engine', 2, @t_P08_T3
        'P08', 4, 'A climb that gains no height burns nothing', 1, @t_P08_T4
        'P08', 5, 'Too little power to climb', 2, @t_P08_T5
        'P09', 1, 'The eight segment fractions', 3, @t_P09_T1
        'P09', 2, 'Bookkeeping and the reserve', 2, @t_P09_T2
        'P09', 3, 'Dispatch on the type, not the position', 1, @t_P09_T3
        'P10', 1, 'The takeoff-weight closure', 2, @t_P10_T1
        'P10', 2, 'A closure that cannot close', 1, @t_P10_T2
        'P10', 3, 'Relaxation', 2, @t_P10_T3
        'P11', 1, 'The constraint analysis sizes the wing and the engine', 3, @t_P11_T1
        'P11', 2, 'Fuel, empty weight and closure on the STEP 0 airplane', 3, @t_P11_T2
        'P11', 3, 'STEP 0 writes the states, not the answer', 2, @t_P11_T3
        'P11', 4, 'The residuals', 2, @t_P11_T4
        'P12', 1, 'The converged airplane', 3, @t_P12_T1
        'P12', 2, 'Every state is relaxed', 2, @t_P12_T2
        'P12', 3, 'The bundle holds the converged airplane', 2, @t_P12_T3
        'P12', 4, 'A different guess, the same airplane, both residuals closed', 2, @t_P12_T4
    };

    results = struct('problem', {}, 'test', {}, 'title', {}, 'weight', {}, 'pass', {}, 'message', {});
    for i = 1:size(T, 1)
        if strlength(only) > 0 && T{i,1} ~= only
            continue;
        end
        ok = true;  msg = "";
        try
            feval(T{i,5});
        catch ME
            ok = false;  msg = string(ME.message);
        end
        results(end+1) = struct('problem', string(T{i,1}), 'test', T{i,2}, ...
            'title', string(T{i,3}), 'weight', T{i,4}, 'pass', ok, 'message', msg); %#ok<AGROW>
        if ok, tag = 'PASS'; else, tag = 'FAIL'; end
        fprintf('RESULT %s T%d %s w=%d  %s\n', T{i,1}, T{i,2}, tag, T{i,4}, T{i,3});
        if ~ok, fprintf('       -> %s\n', msg); end
    end

    earned = sum([results([results.pass]).weight]);
    possible = sum([results.weight]);
    fprintf('\nSCORE %d / %d   (%d of %d tests pass)\n', earned, possible, ...
            nnz([results.pass]), numel(results));
    if strlength(only) == 0 && any(~[results.pass])
        error('run_grader_tests:Failed', '%d test(s) failed.', nnz(~[results.pass]));
    end
end


function t_P01_T1()
% Problem 1, Test 1 - The constructor reads the regression
    obj = ttpa_disciplines();
    assert(abs(obj.prop.k_W_engine - 5.47) <= 1e-12, 'k_W_engine must be read from J.propulsion.engine_weight_coefficient');
    assert(abs(obj.prop.n_W_engine - 0.78) <= 1e-12, 'n_W_engine must be read from J.propulsion.engine_weight_exponent');
    assert(abs(obj.prop.k_L_engine - 0.32) <= 1e-12, 'k_L_engine must be read from J.propulsion.engine_length_coefficient');
    assert(abs(obj.prop.n_L_engine - 0.424) <= 1e-12, 'n_L_engine must be read from J.propulsion.engine_length_exponent');
    assert(isequal(obj.prop.bhp_range(:).', [60 500]), 'bhp_range must be read from J.propulsion.bhp_range_of_validity');
    assert(isstring(obj.prop.engine_scaling_class) && obj.prop.engine_scaling_class == "opposed", 'engine_scaling_class must be the string "opposed"');
end

function t_P01_T2()
% Problem 1, Test 2 - Engine size at P_SL = 600 hp
    obj = ttpa_disciplines();
    obj.prop.P_SL = 600;
    assert(abs(obj.prop.rated_bhp_per_engine() - 300) <= 1e-9, 'the rated power is per ENGINE: P_SL / n_engines');
    [W_total, W_each] = obj.prop.engine_weight();
    assert(abs(W_each - 467.887998) <= 1e-4*467.887998, 'W_each = k_W_engine * bhp^n_W_engine, with bhp of ONE engine');
    assert(abs(W_total - 935.775996) <= 1e-4*935.775996, 'W_total must be n_engines times W_each');
    assert(abs(obj.prop.engine_length() - 3.592935) <= 1e-4*3.592935, 'engine_length = k_L_engine * bhp^n_L_engine, for ONE engine');
end

function t_P01_T3()
% Problem 1, Test 3 - The engine follows P_SL
    obj = ttpa_disciplines();
    obj.prop.P_SL = 700;
    [~, W_each] = obj.prop.engine_weight();
    assert(abs(W_each - 527.667567) <= 1e-4*527.667567, 'engine_weight must be recomputed from the current P_SL');
    assert(abs(obj.prop.engine_length() - 3.835613) <= 1e-4*3.835613, 'engine_length must be recomputed from the current P_SL');
end

function t_P01_T4()
% Problem 1, Test 4 - The range guard
    obj = ttpa_disciplines();
    obj.prop.P_SL = 1200;
    lastwarn('');
    bhp = obj.prop.rated_bhp_per_engine();
    [~, id] = lastwarn;
    assert(strcmp(id, 'TtpaProp:BhpOutOfRange'), 'outside 60-500 bhp the guard must WARN, with identifier TtpaProp:BhpOutOfRange');
    assert(abs(bhp - 600) <= 1e-9, 'the guard must warn AND still return the value');
    obj.prop.P_SL = NaN;
    threw = false;
    try
        obj.prop.rated_bhp_per_engine();
    catch ME
        threw = strcmp(ME.identifier, 'TtpaProp:PowerNotSet');
    end
    assert(threw, 'with P_SL = NaN the guard must error, with identifier TtpaProp:PowerNotSet');
end

function t_P02_T1()
% Problem 2, Test 1 - The constructor reads the sub-blocks
    obj = ttpa_disciplines();
    g = obj.geom;
    assert(abs(g.V_ht - 0.8) <= 1e-12 && abs(g.L_ht - 15) <= 1e-12, 'horizontal_tail: volume coefficient or arm is wrong');
    assert(abs(g.V_vt - 0.065) <= 1e-12 && abs(g.L_vt - 17) <= 1e-12, 'vertical_tail: volume coefficient or arm is wrong');
    assert(abs(g.tc_ht - 0.12) <= 1e-12 && abs(g.tc_vt - 0.12) <= 1e-12, 'tail thickness ratios are wrong');
    assert(abs(g.w_fus - 5.0) <= 1e-12 && abs(g.h_fus - 5.75) <= 1e-12, 'fuselage width or height is wrong');
    assert(abs(g.l_nose + g.l_cabin + g.l_cone - 31.6) <= 1e-9, 'fuselage nose, cabin or tail-cone length is wrong');
    assert(abs(g.d_nacelle - 2.8) <= 1e-12 && abs(g.k_nacelle_length - 2.0) <= 1e-12, 'nacelle diameter or length factor is wrong');
    assert(isnan(g.S_ref), 'S_ref must start as NaN: the sizing loop sets it');
end

function t_P02_T2()
% Problem 2, Test 2 - The exposed wing
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    g = obj.geom;
    assert(abs(g.b - 32.249031) <= 1e-4*32.249031, 'the span is wrong - it is given, check you did not change it');
    assert(abs(g.S_exposed_wing - 102.545508) <= 1e-4*102.545508, 'S_exposed_wing is wrong: S_ref minus the chord integrated across the fuselage width');
end

function t_P02_T3()
% Problem 2, Test 3 - Tail sizing
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    assert(abs(obj.geom.S_ht - 29.660333) <= 1e-4*29.660333, 'S_ht = V_h * S_ref * MAC / L_ht');
    assert(abs(obj.geom.S_vt - 16.029665) <= 1e-4*16.029665, 'S_vt = V_v * S_ref * b / L_vt - the vertical tail uses the SPAN, not the MAC');
end

function t_P02_T4()
% Problem 2, Test 4 - Wetted areas
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    g = obj.geom;
    assert(abs(TtpaGeom.wetted_from_exposed(10, 0.18) - 20.706) <= 1e-9, 'above t/c = 0.05: S_exposed * (1.977 + 0.52 t/c), Raymer Eq. 7.12');
    assert(abs(TtpaGeom.wetted_from_exposed(10, 0.04) - 20.03) <= 1e-9, 'below t/c = 0.05: 2.003 S_exposed, Raymer Eq. 7.11');
    assert(abs(g.S_wet_fuselage - 383.2225) <= 1e-4*383.2225, 'fuselage wetted area: 3.4 (A_top + A_side)/2, Raymer Eq. 7.13');
    assert(abs(g.l_nacelle - 7.185870) <= 1e-4*7.185870, 'l_nacelle = k_nacelle_length times the ENGINE length from the propulsion model');
    assert(abs(g.S_wet_nacelle - 126.420437) <= 1e-4*126.420437, 'S_wet_nacelle = n_engines * pi * d_nacelle * l_nacelle');
    assert(abs(g.S_wet - 812.754284) <= 1e-4*812.754284, 'S_wet must add all five components');
    assert(abs(g.S_wet_over_S_ref - 6.251956) <= 1e-4*6.251956, 'S_wet_over_S_ref = S_wet / S_ref');
end

function t_P02_T5()
% Problem 2, Test 5 - Everything follows S_ref and P_SL, except the fuselage
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    g = obj.geom;
    assert(abs(g.S_ht - 36.761895) <= 1e-4*36.761895, 'S_ht must follow S_ref');
    assert(abs(g.S_vt - 19.867642) <= 1e-4*19.867642, 'S_vt must follow S_ref');
    assert(abs(g.S_wet_over_S_ref - 5.810908) <= 1e-4*5.810908, 'S_wet_over_S_ref must follow S_ref');
    assert(abs(g.S_wet_fuselage - 383.2225) <= 1e-4*383.2225, 'the fuselage is sized by the cabin: it must NOT follow S_ref');
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 700;
    assert(abs(g.S_wet_nacelle - 134.959271) <= 1e-4*134.959271, 'the nacelles must follow P_SL');
    assert(abs(g.S_wet_wing - 209.931164) <= 1e-4*209.931164, 'the wing must NOT follow P_SL');
end

function t_P02_T6()
% Problem 2, Test 6 - Wing fuel volume
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    assert(abs(obj.geom.wing_fuel_volume() - 35.418157) <= 1e-4*35.418157, 'wing_fuel_volume is wrong: check tau = (t/c)_tip/(t/c)_root and the (1 + lambda)^2 denominator');
end

function t_P03_T1()
% Problem 3, Test 1 - Injection and the constructor
    obj = ttpa_disciplines();
    assert(obj.aero.geom == obj.geom, 'obj.aero.geom must be the SAME TtpaGeom object that ttpa_disciplines injected');
    assert(abs(obj.aero.Cfe - 0.0045) <= 1e-12, 'Cfe must be read from J.aerodynamics.Cfe');
    assert(abs(obj.aero.CD0_reference - 0.028) <= 1e-12, 'CD0_reference must be read from J.aerodynamics.CD0_clean');
    assert(obj.aero.AR == obj.geom.AR, 'AR must come from the geometry model');
end

function t_P03_T2()
% Problem 3, Test 2 - C_D0 and the polar at S_ref = 130, P_SL = 600
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    assert(abs(obj.aero.CD0 - 0.02813380) <= 1e-4*0.02813380, 'CD0 = Cfe * S_wet / S_ref');
    assert(abs(obj.aero.LD_max - 13.454791) <= 1e-4*13.454791, 'LD_max must use the new CD0');
    polar = obj.aero.drag_polar(get_state(0));
    assert(abs(polar.CD0 - 0.02813380) <= 1e-4*0.02813380, 'drag_polar must return the live CD0');
    cfg = obj.aero.get_config_polar(get_state(0), struct('config', "landing_flaps_gear_down", 'propeller_stopped', false));
    assert(abs(cfg.CD0 - 0.11313380) <= 1e-4*0.11313380, 'the configuration polars must build on the live CD0');
end

function t_P03_T3()
% Problem 3, Test 3 - C_D0 follows the wing and the engine
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    assert(abs(obj.aero.CD0 - 0.02614909) <= 1e-4*0.02614909, 'CD0 must follow S_ref');
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 700;
    assert(abs(obj.aero.CD0 - 0.02842938) <= 1e-4*0.02842938, 'CD0 must follow P_SL, through the nacelle wetted area');
    assert(abs(obj.aero.e - 0.810592) <= 1e-4*0.810592, 'the Oswald factor does not depend on size');
end

function t_P04_T1()
% Problem 4, Test 1 - Empty weight II, all seven rows
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    bd = obj.wts.OEW_breakdown(5400);
    assert(abs(bd.wing - 256.363770) <= 1e-4*256.363770, 'wing row: 2.5 lb/ft^2 times the EXPOSED wing area');
    assert(abs(bd.horizontal_tail - 59.320667) <= 1e-4*59.320667, 'horizontal tail row: 2.0 lb/ft^2 times S_ht');
    assert(abs(bd.vertical_tail - 32.059331) <= 1e-4*32.059331, 'vertical tail row: 2.0 lb/ft^2 times S_vt');
    assert(abs(bd.fuselage - 536.5115) <= 1e-4*536.5115, 'fuselage row: 1.4 lb/ft^2 times the fuselage WETTED area');
    assert(abs(bd.landing_gear - 307.8) <= 1e-9, 'landing gear row: 0.057 W_TO');
    assert(abs(bd.installed_engine - 1310.086394) <= 1e-4*1310.086394, 'installed engine row: 1.4 times ALL the bare engines');
    assert(abs(bd.all_else_empty - 540) <= 1e-9, 'all-else row: 0.10 W_TO');
    assert(abs(bd.total - 3042.141662) <= 1e-4*3042.141662, 'total must add all seven rows');
    assert(abs(obj.wts.OEW(5400) - bd.total) <= 1e-9, 'OEW must return the total of OEW_breakdown');
end

function t_P04_T2()
% Problem 4, Test 2 - Evaluated at the PASSED weight
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.wts.W_TO   = 1;
    bd = obj.wts.OEW_breakdown(6000);
    assert(abs(bd.landing_gear - 342) <= 1e-9, 'evaluate every weight-dependent row at the PASSED W_TO, never obj.W_TO');
    assert(abs(bd.all_else_empty - 600) <= 1e-9, 'evaluate every weight-dependent row at the PASSED W_TO, never obj.W_TO');
    assert(abs(bd.total - 3136.341662) <= 1e-4*3136.341662, 'the total at W_TO = 6000 is wrong');
end

function t_P04_T3()
% Problem 4, Test 3 - The build-up follows the geometry
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    bd = obj.wts.OEW_breakdown(5400);
    assert(abs(bd.wing - 301.024518) <= 1e-4*301.024518, 'the wing row must follow S_ref');
    assert(abs(bd.horizontal_tail - 73.523789) <= 1e-4*73.523789, 'the tail rows must follow S_ref');
    assert(abs(bd.fuselage - 536.5115) <= 1e-4*536.5115, 'the fuselage row must not follow S_ref');
    assert(abs(bd.total - 3108.681484) <= 1e-4*3108.681484, 'the total at S_ref = 150 is wrong');
end

function t_P04_T4()
% Problem 4, Test 4 - Empty weight III
    obj = ttpa_disciplines();
    obj.geom.S_ref   = 130;
    obj.prop.P_SL    = 600;
    obj.wts.method   = "raymer_ga_III";
    obj.wts.W_energy = 1150;
    bd = obj.wts.OEW_breakdown(5400);
    assert(abs(bd.wing - 338.963531) <= 1e-4*338.963531, 'Raymer Eq. 15.46 wing weight is wrong');
    assert(abs(bd.installed_engine - 1491.688239) <= 1e-4*1491.688239, 'Raymer Eq. 15.52: 2.575 W_en^0.922 N_en, with W_en ONE bare engine');
    assert(abs(bd.total - 3306.343266) <= 1e-4*3306.343266, 'the Empty weight III total is wrong');
    obj.wts.W_energy = NaN;
    bd = obj.wts.OEW_breakdown(5400);
    assert(abs(bd.wing - 330.704826) <= 1e-4*330.704826, 'with no fuel weight yet the W_fw term is ignored (set to 1)');
end

function t_P04_T5()
% Problem 4, Test 5 - An unknown method stops the analysis
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.wts.method = "napkin";
    threw = false;
    try
        obj.wts.OEW_breakdown(5400);
    catch ME
        threw = strcmp(ME.identifier, 'TtpaWeights:UndefinedMethod');
    end
    assert(threw, 'an unknown weight method must error, with identifier TtpaWeights:UndefinedMethod');
end

function t_P05_T1()
% Problem 5, Test 1 - The power-index method is unchanged
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.cons(6).method = "power_index";
    WP_exp = [8.432052 11.242735];
    WP = constraint_cruise_speed([30 40], obj, 6);
    assert(all(abs(WP - WP_exp) <= 1e-4*WP_exp), 'with method "power_index" the IHW2 answer must be unchanged');
end

function t_P05_T2()
% Problem 5, Test 2 - The drag-based power balance
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    WP_exp = [7.126195 8.679851 9.052354];
    [WP, extra] = constraint_cruise_speed([30 40 43], obj, 6);
    assert(isequal(size(WP), [1 3]), 'WP_max must be the same size as WS - use element-by-element operators');
    assert(all(abs(WP - WP_exp) <= 1e-4*WP_exp), 'the drag-based power-loading limit is wrong');
    assert(abs(extra.CL(2) - 0.375787) <= 1e-4*0.375787, 'C_L = beta*(W/S)/q');
    assert(abs(extra.LD(2) - 10.716711) <= 1e-4*10.716711, 'L/D at the required speed is wrong');
end

function t_P05_T3()
% Problem 5, Test 3 - The limit follows the drag polar
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    WP_exp = [7.596888 9.200607 9.578309];
    WP = constraint_cruise_speed([30 40 43], obj, 6);
    assert(all(abs(WP - WP_exp) <= 1e-4*WP_exp), 'the drag-based limit must follow the drag polar, and so the wing');
    obj.cons(6).method = "guess";
    threw = false;
    try
        constraint_cruise_speed(40, obj, 6);
    catch ME
        threw = strcmp(ME.identifier, 'constraint_cruise_speed:UndefinedMethod');
    end
    assert(threw, 'an unknown method must error, with identifier constraint_cruise_speed:UndefinedMethod');
end

function t_P06_T1()
% Problem 6, Test 1 - The cruise weight fraction
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [W_out, fuel_used, WF] = segment_cruise_L2(5000, obj, 3);
    assert(abs(WF - 0.83416445) <= 1e-4*0.83416445, 'the cruise weight fraction is wrong');
    assert(abs(fuel_used - 829.177771) <= 1e-4*829.177771, 'fuel_used = (1 - WF) * W_in');
    assert(abs(W_out - 4170.822229) <= 1e-4*4170.822229, 'W_out = W_in * WF');
end

function t_P06_T2()
% Problem 6, Test 2 - Flown at the real lift coefficient
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [~, ~, WF, info] = segment_cruise_L2(5000, obj, 3);
    assert(info.n_sub == 12, 'n_sub must be read from obj.miss.cruise_segments');
    assert(abs(info.CL - 0.33357474) <= 1e-4*0.33357474, 'the mean cruise C_L is wrong: C_L = W/(q*S_ref) in every piece');
    assert(abs(info.LD - 9.918921) <= 1e-4*9.918921, 'the mean cruise L/D is wrong');
    assert(WF < 0.87501940 - 0.01, 'flying at L/D_max is the IHW1 answer, not this one');
end

function t_P06_T3()
% Problem 6, Test 3 - Flown with the current wing
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    [~, ~, WF] = segment_cruise_L2(5000, obj, 3);
    assert(abs(WF - 0.82790073) <= 1e-4*0.82790073, 'the cruise must be flown with the CURRENT wing, obj.geom.S_ref');
end

function t_P06_T4()
% Problem 6, Test 4 - The sub-segment count
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.miss.cruise_segments = 1;
    [~, ~, WF] = segment_cruise_L2(5000, obj, 3);
    assert(abs(WF - 0.84221048) <= 1e-4*0.84221048, 'with one piece the whole cruise is flown at the starting C_L');
    obj.miss.cruise_segments = 48;
    [~, ~, WF] = segment_cruise_L2(5000, obj, 3);
    assert(abs(WF - 0.83354562) <= 1e-4*0.83354562, 'the range must be split evenly across n_sub pieces');
end

function t_P07_T1()
% Problem 7, Test 1 - The loiter weight fraction
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [W_out, fuel_used, WF, info] = segment_loiter_L2(4200, obj, 6);
    assert(abs(WF - 0.98865969) <= 1e-5*0.98865969, 'the loiter weight fraction is wrong');
    assert(abs(fuel_used - 47.629301) <= 1e-4*47.629301, 'fuel_used = (1 - WF) * W_in');
    assert(abs(W_out - 4152.370699) <= 1e-6*4152.370699, 'W_out = W_in * WF');
    assert(abs(info.CL - 0.74621120) <= 1e-4*0.74621120, 'C_L = W/(q*S_ref) at the loiter speed and altitude');
    assert(abs(info.LD - 13.453388) <= 1e-4*13.453388, 'L/D at the loiter C_L is wrong');
end

function t_P07_T2()
% Problem 7, Test 2 - Flown with the current wing, not the IHW1 rule
    obj = ttpa_disciplines();
    obj.geom.S_ref = 150;
    obj.prop.P_SL  = 600;
    [~, ~, WF] = segment_loiter_L2(4200, obj, 6);
    assert(abs(WF - 0.98898625) <= 1e-5*0.98898625, 'the loiter must be flown with the CURRENT wing, obj.geom.S_ref');
    obj.geom.S_ref = 130;
    [~, ~, WF] = segment_loiter_L2(4200, obj, 6);
    assert(abs(WF - 0.98691784) > 1e-4, 'L/D = 0.866 L/D_max is the IHW1 answer, not this one');
end

function t_P08_T1()
% Problem 8, Test 1 - The first climb, sea level to 8000 ft
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [W_out, fuel_used, WF, info] = segment_climb_L2(4920, obj, 2);
    assert(abs(fuel_used - 14.976315) <= 1e-4*14.976315, 'the fuel burned from sea level to 8000 ft is wrong');
    assert(abs(W_out - 4905.023685) <= 1e-6*4905.023685, 'W_out = W_in * WF');
    assert(abs(WF - 0.99695603) <= 1e-6*0.99695603, 'WF = W at the top of the climb / W_in');
    assert(abs(info.CL - 1.3112817) <= 1e-4*1.3112817, 'climb at C_L = sqrt(3*CD0/K1), the minimum-power lift coefficient');
    assert(abs(info.time_hr - 0.07925085) <= 1e-4*0.07925085, 'the time to climb is wrong');
end

function t_P08_T2()
% Problem 8, Test 2 - The second climb starts where the previous segment ended
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [~, fuel_used] = segment_climb_L2(4000, obj, 5);
    assert(abs(fuel_used - 5.189087) <= 1e-4*5.189087, 'segment 5 climbs from the altitude segment 4 ended at, 0 ft, to 4000 ft');
    obj.miss.segments(4).alt_ft = 2000;
    [~, fuel_used] = segment_climb_L2(4000, obj, 5);
    assert(abs(fuel_used - 2.631546) <= 1e-4*2.631546, 'with the descent ending at 2000 ft, segment 5 climbs only from 2000 to 4000 ft - take h_start from segment seg_no - 1');
end

function t_P08_T3()
% Problem 8, Test 3 - The climb follows the engine
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 800;
    [~, fuel_used] = segment_climb_L2(4920, obj, 2);
    assert(abs(fuel_used - 13.303155) <= 1e-4*13.303155, 'the climb must use the CURRENT obj.prop.P_SL');
end

function t_P08_T4()
% Problem 8, Test 4 - A climb that gains no height burns nothing
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.miss.segments(2).alt_ft = 0;
    [W_out, fuel_used, WF] = segment_climb_L2(4920, obj, 2);
    assert(WF == 1 && fuel_used == 0 && W_out == 4920, 'a climb that gains no height must return WF = 1 and burn nothing');
end

function t_P08_T5()
% Problem 8, Test 5 - Too little power to climb
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 60;
    threw = false;
    try
        segment_climb_L2(4920, obj, 2);
    catch ME
        threw = strcmp(ME.identifier, 'segment_climb_L2:CannotClimb');
    end
    assert(threw, 'with too little power the climb must stop with identifier segment_climb_L2:CannotClimb');
end

function t_P09_T1()
% Problem 9, Test 1 - The eight segment fractions
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [fuel_burned, segment_weight, segment_wf] = run_mission_L2(5000, obj);
    wf_exp = [0.984 0.99695603 0.83206056 0.992 0.99869593 0.98864535 0.992 0.992];
    assert(isequal(size(segment_wf), [1 8]), 'one weight fraction per segment');
    assert(all(abs(segment_wf - wf_exp) <= 1e-5*wf_exp), 'the segment weight fractions are wrong');
    assert(abs(sum(fuel_burned) - 1066.267093) <= 1e-4*1066.267093, 'the total mission fuel before reserve is wrong');
    assert(abs(segment_weight(end) - 3933.732907) <= 1e-4*3933.732907, 'the final weight is wrong');
end

function t_P09_T2()
% Problem 9, Test 2 - Bookkeeping and the reserve
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    [fuel_burned, segment_weight, segment_wf] = run_mission_L2(5000, obj);
    assert(abs(segment_weight(1) - 5000) <= 1e-12, 'segment_weight(1) is W_TO');
    assert(all(abs(segment_weight(2:end) - segment_weight(1:end-1).*segment_wf) <= 1e-9*5000), 'each segment must start at the weight the previous one ended at');
    assert(all(abs(fuel_burned - segment_weight(1:end-1).*(1 - segment_wf)) <= 1e-9*5000), 'fuel_burned(k) = W_in(k) * (1 - WF(k))');
    W_fuel = mission_fuel(5000, obj);
    assert(abs(W_fuel - 1130.243119) <= 1e-4*1130.243119, 'mission_fuel must see YOUR segment fuel; it adds the 6 % reserve');
end

function t_P09_T3()
% Problem 9, Test 3 - Dispatch on the type, not the position
    obj = ttpa_disciplines();
    obj.geom.S_ref = 130;
    obj.prop.P_SL  = 600;
    obj.miss.segments(5:6) = [];
    [fuel_burned, ~, segment_wf] = run_mission_L2(5000, obj);
    wf_exp = [0.984 0.99695603 0.83206056 0.992 0.992 0.992];
    assert(isequal(size(segment_wf), [1 6]), 'the loop must run over however many segments the profile has');
    assert(all(abs(segment_wf - wf_exp) <= 1e-5*wf_exp), 'with the loiter removed, segments 5 and 6 are a descent and a landing: switch on the segment TYPE');
    assert(abs(sum(fuel_burned) - 1015.892385) <= 1e-4*1015.892385, 'the fuel of the shortened mission is wrong');
end

function t_P10_T1()
% Problem 10, Test 1 - The takeoff-weight closure
    [W_new, denom] = SizingSteps.togw_update(1200, 3000, 1150, 5400);
    assert(abs(denom - 0.231481481) <= 1e-8, 'denom = 1 - W_fuel/W_TO - W_OEW/W_TO');
    assert(abs(W_new - 5184) <= 1e-6, 'W_new = W_payload / denom');
end

function t_P10_T2()
% Problem 10, Test 2 - A closure that cannot close
    [W_new, denom] = SizingSteps.togw_update(1200, 3500, 2000, 5400);
    assert(isnan(W_new), 'when denom <= 0 no positive weight closes: return NaN');
    assert(abs(denom - (1 - 2000/5400 - 3500/5400)) <= 1e-12, 'denom must still be returned when it is negative');
end

function t_P10_T3()
% Problem 10, Test 3 - Relaxation
    assert(abs(SizingSteps.relax(5000, 6000, 0.45) - 5450) <= 1e-9, 'x = x_old + w*(x_new - x_old)');
    assert(abs(SizingSteps.relax(5000, 6000, 1) - 6000) <= 1e-9, 'w = 1 is the full step');
    assert(abs(SizingSteps.relax(606.149, 606.149, 0.2) - 606.149) <= 1e-12, 'at the fixed point relaxation changes nothing');
    assert(abs(SizingSteps.relax(6000, 5000, 0.3) - 5700) <= 1e-9, 'relaxation must work in both directions');
end

function t_P11_T1()
% Problem 11, Test 1 - The constraint analysis sizes the wing and the engine
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    row = sizing_pass(obj, W0, P0, S0, WS_sweep);
    assert(abs(row.WS - 43.240424) <= 1e-5*43.240424, 'W/S must be the least-engine corner from matching_envelope (its 4th output)');
    assert(abs(row.WP - 9.0833073) <= 1e-5*9.0833073, 'W/P must be the least-engine corner (its 5th output)');
    assert(abs(row.S_ref_new - 115.632538) <= 1e-5*115.632538, 'S_new = W0 / (W/S)');
    assert(abs(row.P_SL_new - 550.460294) <= 1e-5*550.460294, 'P_new = W0 / (W/P): power loading is inverted, so DIVIDE');
end

function t_P11_T2()
% Problem 11, Test 2 - Fuel, empty weight and closure on the STEP 0 airplane
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    row = sizing_pass(obj, W0, P0, S0, WS_sweep);
    assert(abs(row.CD0 - 0.02812221) <= 1e-5*0.02812221, 'the pass must be flown by the airplane written in STEP 0 (S0 and P0), not by S_new');
    assert(abs(row.W_fuel - 1124.492673) <= 1e-5*1124.492673, 'the mission fuel is evaluated at W0, on the STEP 0 airplane');
    assert(abs(row.OEW - 2871.915932) <= 1e-5*2871.915932, 'the empty weight is built at W0, from the STEP 0 airplane');
    assert(abs(row.W_TO_new - 5978.528744) <= 1e-5*5978.528744, 'W_new is the takeoff-weight closure at W0');
end

function t_P11_T3()
% Problem 11, Test 3 - STEP 0 writes the states, not the answer
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    obj.geom.S_ref = 200;
    obj.prop.P_SL  = 900;
    row = sizing_pass(obj, W0, P0, S0, WS_sweep);
    assert(abs(obj.geom.S_ref - S0) <= 1e-12 && abs(obj.prop.P_SL - P0) <= 1e-12, 'STEP 0 writes P0 and S0 into the airplane; S_new and P_new are NOT written back');
    assert(abs(row.W_TO_new - 5978.528744) <= 1e-5*5978.528744, 'the pass must not depend on what the airplane held before it was called');
end

function t_P11_T4()
% Problem 11, Test 4 - The residuals
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    row = sizing_pass(obj, W0, P0, S0, WS_sweep);
    assert(abs(row.res_W - 0.16367384) <= 1e-5*0.16367384, 'res_W = |W_new - W0| / W_new');
    assert(abs(row.res_P - 0.01802083) <= 1e-4*0.01802083, 'res_P = |P_new - P0| / P_new');
    assert(abs(row.res_S - 0.11101946) <= 1e-5*0.11101946, 'res_S = |S_new - S0| / S_new');
end

function t_P12_T1()
% Problem 12, Test 1 - The converged airplane
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    opts = struct('W0', W0, 'P0', P0, 'S0', S0, 'WS_sweep', WS_sweep, ...
                  'tol', J.sizing.tol_rel, 'max_iter', J.sizing.max_iter, ...
                  'relax', J.sizing.relaxation);
    [hist, converged, state] = sizing_mainloop(obj, opts);
    assert(converged, 'the loop must report converged = true');
    assert(abs(state.W0 - 5414.742648) <= 1e-5*5414.742648, 'the converged W_TO is wrong');
    assert(abs(state.P0 - 606.148989) <= 1e-5*606.148989, 'the converged P_SL is wrong');
    assert(abs(state.S0 - 125.224206) <= 1e-5*125.224206, 'the converged S_ref is wrong');
    assert(state.n_iter == 34 && numel(hist) == 34, 'at relaxation 0.45 the loop closes in 34 passes: test BOTH residuals against tol');
end

function t_P12_T2()
% Problem 12, Test 2 - Every state is relaxed
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    opts = struct('W0', W0, 'P0', P0, 'S0', S0, 'WS_sweep', WS_sweep, ...
                  'tol', J.sizing.tol_rel, 'max_iter', J.sizing.max_iter, ...
                  'relax', J.sizing.relaxation);
    hist = sizing_mainloop(obj, opts);
    assert(abs(hist(2).W_TO - 5440.337935) <= 1e-6*5440.337935, 'pass 2 must start from W0 + w*(W_new - W0), not from W_new');
    assert(abs(hist(2).P_SL - 545.004430) <= 1e-6*545.004430, 'relax the power as well');
    assert(abs(hist(2).S_ref - 122.693142) <= 1e-6*122.693142, 'relax the wing area as well');
end

function t_P12_T3()
% Problem 12, Test 3 - The bundle holds the converged airplane
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    opts = struct('W0', W0, 'P0', P0, 'S0', S0, 'WS_sweep', WS_sweep, ...
                  'tol', J.sizing.tol_rel, 'max_iter', J.sizing.max_iter, ...
                  'relax', J.sizing.relaxation);
    [hist, ~, state] = sizing_mainloop(obj, opts);
    assert(abs(obj.geom.S_ref - state.S0) <= 1e-12 && abs(obj.prop.P_SL - state.P0) <= 1e-12, 'on return obj must hold the converged S_ref and P_SL');
    assert(abs(state.W0 - hist(end).W_TO_new) <= 1e-12, 'on convergence take the pass''s own answer, unrelaxed');
end

function t_P12_T4()
% Problem 12, Test 4 - A different guess, the same airplane, both residuals closed
    obj = ttpa_disciplines();
    J  = jsondecode(fileread(ttpa_requirements_path()));
    W0 = J.sizing.W_TO_guess_lbf;
    S0 = J.sizing.S_ref_guess_ft2;
    P0 = W0 / J.constraints.design_point.power_loading_lb_per_hp;
    obj.geom.S_ref = S0;
    obj.prop.P_SL  = P0;
    WS_sweep = wing_loading_sweep(obj);
    opts = struct('W0', W0, 'P0', P0, 'S0', S0, 'WS_sweep', WS_sweep, ...
                  'tol', J.sizing.tol_rel, 'max_iter', J.sizing.max_iter, ...
                  'relax', J.sizing.relaxation);
    opts.W0 = 8000;
    opts.P0 = 900;
    opts.S0 = 180;
    [hist, converged, state] = sizing_mainloop(obj, opts);
    assert(converged && abs(state.W0 - 5414.742648) <= 1e-5*5414.742648, 'a different starting guess must reach the same airplane');
    assert(hist(end).res_W < opts.tol && hist(end).res_P < opts.tol, 'the loop may stop only when BOTH residuals are below tol - from this guess the power settles last');
    assert(state.n_iter == 33, 'from this guess the loop closes in 33 passes when both residuals are tested');
end
